http_interactions:
- recorded_at: Thu, 19 Jan 2023 19:59:42 GMT
  request:
    body: null
    headers:
      Accept:
      - application/json
    method: GET
    uri: https://api.datadoghq.com/api/v2/monitor/policy
  response:
    body:
      encoding: UTF-8
      string: '{"data":[]}

        '
    headers:
      Content-Type:
      - application/json
    status:
      code: 200
      message: OK
recorded_with: VCR 6.0.0
