http_interactions:
- recorded_at: Fri, 17 Dec 2021 16:05:20 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"name":"Test-Edit_an_application_key_returns_OK_response-1639757120"},"type":"application_keys"}}'
    headers:
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Length:
      - '375'
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      Content-Type:
      - application/json
      Date:
      - Fri, 17 Dec 2021 16:05:20 GMT
      Pragma:
      - no-cache
      Strict-Transport-Security:
      - max-age=15724800;
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Ratelimit-Limit:
      - '400'
      X-Ratelimit-Period:
      - '3600'
      X-Ratelimit-Remaining:
      - '388'
      X-Ratelimit-Reset:
      - '3280'
    method: POST
    uri: https://api.datadoghq.com/api/v2/current_user/application_keys
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"type":"application_keys","id":"82a1a46d-7acc-4fcd-a448-c5993752640a","attributes":{"name":"Test-Edit_an_application_key_returns_OK_response-1639757120","created_at":"2021-12-17T16:05:20.518462+00:00","last4":"beef","key":"deaddcc81a44288fbbbfb15efe1203df034abeef"},"relationships":{"owned_by":{"data":{"type":"users","id":"3ad549bf-eba0-11e9-a77a-0705486660d0"}}}}}'
    status:
      code: 201
      message: Created
- recorded_at: Fri, 17 Dec 2021 16:05:20 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"id":"82a1a46d-7acc-4fcd-a448-c5993752640a","type":"application_keys","attributes":{"name":"Test-Edit_an_application_key_returns_OK_response-1639757120-updated"}}}'
    headers:
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Length:
      - '334'
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      Content-Type:
      - application/json
      Date:
      - Fri, 17 Dec 2021 16:05:20 GMT
      Pragma:
      - no-cache
      Strict-Transport-Security:
      - max-age=15724800;
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Ratelimit-Limit:
      - '400'
      X-Ratelimit-Period:
      - '3600'
      X-Ratelimit-Remaining:
      - '387'
      X-Ratelimit-Reset:
      - '3280'
    method: PATCH
    uri: https://api.datadoghq.com/api/v2/application_keys/82a1a46d-7acc-4fcd-a448-c5993752640a
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"type":"application_keys","id":"82a1a46d-7acc-4fcd-a448-c5993752640a","attributes":{"name":"Test-Edit_an_application_key_returns_OK_response-1639757120-updated","created_at":"2021-12-17T16:05:20.518462+00:00","last4":"beef"},"relationships":{"owned_by":{"data":{"type":"users","id":"3ad549bf-eba0-11e9-a77a-0705486660d0"}}}}}'
    status:
      code: 200
      message: OK
- recorded_at: Fri, 17 Dec 2021 16:05:20 GMT
  request:
    body: null
    headers:
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      Date:
      - Fri, 17 Dec 2021 16:05:21 GMT
      Pragma:
      - no-cache
      Strict-Transport-Security:
      - max-age=15724800;
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Ratelimit-Limit:
      - '400'
      X-Ratelimit-Period:
      - '3600'
      X-Ratelimit-Remaining:
      - '386'
      X-Ratelimit-Reset:
      - '3279'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/current_user/application_keys/82a1a46d-7acc-4fcd-a448-c5993752640a
  response:
    body:
      encoding: UTF-8
      string: ''
    status:
      code: 204
      message: No Content
recorded_with: VCR 6.0.0
