FROM ruby:2.7

WORKDIR /tmp/spec-repo/generated/datadog-api-client-ruby

COPY . .
RUN bundle config set system 'true' && \
    bundle install

CMD ["/tmp/spec-repo/generated/datadog-api-client-ruby/run-tests.sh"]
