=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'cgi'

module DatadogAPIClient::V2
  class OAuth2ClientPublicAPI
    attr_accessor :api_client

    def initialize(api_client = DatadogAPIClient::APIClient.default)
      @api_client = api_client
    end

    # Delete an OAuth2 client scopes restriction.
    #
    # @see #delete_scopes_restriction_with_http_info
    def delete_scopes_restriction(client_uuid, opts = {})
      delete_scopes_restriction_with_http_info(client_uuid, opts)
      nil
    end

    # Delete an OAuth2 client scopes restriction.
    #
    # Delete the scopes restriction configured for the OAuth2 client.
    #
    # @param client_uuid [UUID] UUID of the OAuth2 client.
    # @param opts [Hash] the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def delete_scopes_restriction_with_http_info(client_uuid, opts = {})
      unstable_enabled = @api_client.config.unstable_operations["v2.delete_scopes_restriction".to_sym]
      if unstable_enabled
        @api_client.config.logger.warn format("Using unstable operation '%s'", "v2.delete_scopes_restriction")
      else
        raise DatadogAPIClient::APIError.new(message: format("Unstable operation '%s' is disabled", "v2.delete_scopes_restriction"))
      end

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OAuth2ClientPublicAPI.delete_scopes_restriction ...'
      end
      # verify the required parameter 'client_uuid' is set
      if @api_client.config.client_side_validation && client_uuid.nil?
        fail ArgumentError, "Missing the required parameter 'client_uuid' when calling OAuth2ClientPublicAPI.delete_scopes_restriction"
      end
      # resource path
      local_var_path = '/api/v2/oauth2/clients/{client_uuid}/scopes_restriction'.sub('{client_uuid}', CGI.escape(client_uuid.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :delete_scopes_restriction,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Delete, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OAuth2ClientPublicAPI#delete_scopes_restriction\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get OAuth2 well-known sites.
    #
    # @see #get_o_auth2_well_known_sites_with_http_info
    def get_o_auth2_well_known_sites(opts = {})
      data, _status_code, _headers = get_o_auth2_well_known_sites_with_http_info(opts)
      data
    end

    # Get OAuth2 well-known sites.
    #
    # Retrieve the list of public OAuth2 sites available for the current environment. This endpoint is used for OAuth2 discovery and returns sites where users can authenticate.
    #
    # @param opts [Hash] the optional parameters
    # @return [Array<(OAuth2WellKnownSitesResponse, Integer, Hash)>] OAuth2WellKnownSitesResponse data, response status code and response headers
    def get_o_auth2_well_known_sites_with_http_info(opts = {})
      unstable_enabled = @api_client.config.unstable_operations["v2.get_o_auth2_well_known_sites".to_sym]
      if unstable_enabled
        @api_client.config.logger.warn format("Using unstable operation '%s'", "v2.get_o_auth2_well_known_sites")
      else
        raise DatadogAPIClient::APIError.new(message: format("Unstable operation '%s' is disabled", "v2.get_o_auth2_well_known_sites"))
      end

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OAuth2ClientPublicAPI.get_o_auth2_well_known_sites ...'
      end
      # resource path
      local_var_path = '/api/v2/oauth2/.well-known/sites'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'OAuth2WellKnownSitesResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :get_o_auth2_well_known_sites,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Get, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OAuth2ClientPublicAPI#get_o_auth2_well_known_sites\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get an OAuth2 client scopes restriction.
    #
    # @see #get_scopes_restriction_with_http_info
    def get_scopes_restriction(client_uuid, opts = {})
      data, _status_code, _headers = get_scopes_restriction_with_http_info(client_uuid, opts)
      data
    end

    # Get an OAuth2 client scopes restriction.
    #
    # Get the scopes restriction configured for the OAuth2 client.
    #
    # @param client_uuid [UUID] UUID of the OAuth2 client.
    # @param opts [Hash] the optional parameters
    # @return [Array<(OAuthScopesRestrictionResponse, Integer, Hash)>] OAuthScopesRestrictionResponse data, response status code and response headers
    def get_scopes_restriction_with_http_info(client_uuid, opts = {})
      unstable_enabled = @api_client.config.unstable_operations["v2.get_scopes_restriction".to_sym]
      if unstable_enabled
        @api_client.config.logger.warn format("Using unstable operation '%s'", "v2.get_scopes_restriction")
      else
        raise DatadogAPIClient::APIError.new(message: format("Unstable operation '%s' is disabled", "v2.get_scopes_restriction"))
      end

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OAuth2ClientPublicAPI.get_scopes_restriction ...'
      end
      # verify the required parameter 'client_uuid' is set
      if @api_client.config.client_side_validation && client_uuid.nil?
        fail ArgumentError, "Missing the required parameter 'client_uuid' when calling OAuth2ClientPublicAPI.get_scopes_restriction"
      end
      # resource path
      local_var_path = '/api/v2/oauth2/clients/{client_uuid}/scopes_restriction'.sub('{client_uuid}', CGI.escape(client_uuid.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'OAuthScopesRestrictionResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :get_scopes_restriction,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Get, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OAuth2ClientPublicAPI#get_scopes_restriction\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Register an OAuth2 client.
    #
    # @see #register_o_auth_client_with_http_info
    def register_o_auth_client(body, opts = {})
      data, _status_code, _headers = register_o_auth_client_with_http_info(body, opts)
      data
    end

    # Register an OAuth2 client.
    #
    # Register an OAuth2 client using the Dynamic Client Registration protocol defined in RFC 7591.
    #
    # @param body [OAuthClientRegistrationRequest] 
    # @param opts [Hash] the optional parameters
    # @return [Array<(OAuthClientRegistrationResponse, Integer, Hash)>] OAuthClientRegistrationResponse data, response status code and response headers
    def register_o_auth_client_with_http_info(body, opts = {})
      unstable_enabled = @api_client.config.unstable_operations["v2.register_o_auth_client".to_sym]
      if unstable_enabled
        @api_client.config.logger.warn format("Using unstable operation '%s'", "v2.register_o_auth_client")
      else
        raise DatadogAPIClient::APIError.new(message: format("Unstable operation '%s' is disabled", "v2.register_o_auth_client"))
      end

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OAuth2ClientPublicAPI.register_o_auth_client ...'
      end
      # verify the required parameter 'body' is set
      if @api_client.config.client_side_validation && body.nil?
        fail ArgumentError, "Missing the required parameter 'body' when calling OAuth2ClientPublicAPI.register_o_auth_client"
      end
      # resource path
      local_var_path = '/api/v2/oauth2/register'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(body)

      # return_type
      return_type = opts[:debug_return_type] || 'OAuthClientRegistrationResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :register_o_auth_client,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Post, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OAuth2ClientPublicAPI#register_o_auth_client\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Upsert an OAuth2 client scopes restriction.
    #
    # @see #upsert_scopes_restriction_with_http_info
    def upsert_scopes_restriction(client_uuid, body, opts = {})
      data, _status_code, _headers = upsert_scopes_restriction_with_http_info(client_uuid, body, opts)
      data
    end

    # Upsert an OAuth2 client scopes restriction.
    #
    # Create or update the scopes restriction configured for the OAuth2 client.
    #
    # @param client_uuid [UUID] UUID of the OAuth2 client.
    # @param body [UpsertOAuthScopesRestrictionRequest] 
    # @param opts [Hash] the optional parameters
    # @return [Array<(OAuthScopesRestrictionResponse, Integer, Hash)>] OAuthScopesRestrictionResponse data, response status code and response headers
    def upsert_scopes_restriction_with_http_info(client_uuid, body, opts = {})
      unstable_enabled = @api_client.config.unstable_operations["v2.upsert_scopes_restriction".to_sym]
      if unstable_enabled
        @api_client.config.logger.warn format("Using unstable operation '%s'", "v2.upsert_scopes_restriction")
      else
        raise DatadogAPIClient::APIError.new(message: format("Unstable operation '%s' is disabled", "v2.upsert_scopes_restriction"))
      end

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OAuth2ClientPublicAPI.upsert_scopes_restriction ...'
      end
      # verify the required parameter 'client_uuid' is set
      if @api_client.config.client_side_validation && client_uuid.nil?
        fail ArgumentError, "Missing the required parameter 'client_uuid' when calling OAuth2ClientPublicAPI.upsert_scopes_restriction"
      end
      # verify the required parameter 'body' is set
      if @api_client.config.client_side_validation && body.nil?
        fail ArgumentError, "Missing the required parameter 'body' when calling OAuth2ClientPublicAPI.upsert_scopes_restriction"
      end
      # resource path
      local_var_path = '/api/v2/oauth2/clients/{client_uuid}/scopes_restriction'.sub('{client_uuid}', CGI.escape(client_uuid.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(body)

      # return_type
      return_type = opts[:debug_return_type] || 'OAuthScopesRestrictionResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :upsert_scopes_restriction,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Post, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OAuth2ClientPublicAPI#upsert_scopes_restriction\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
