=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'cgi'

module DatadogAPIClient::V2
  class OCIIntegrationAPI
    attr_accessor :api_client

    def initialize(api_client = DatadogAPIClient::APIClient.default)
      @api_client = api_client
    end

    # Create tenancy config.
    #
    # @see #create_tenancy_config_with_http_info
    def create_tenancy_config(body, opts = {})
      data, _status_code, _headers = create_tenancy_config_with_http_info(body, opts)
      data
    end

    # Create tenancy config.
    #
    # Create a new tenancy config to establish monitoring and data collection from your OCI environment. Requires OCI authentication credentials and tenancy details. Warning: Datadog recommends interacting with this endpoint only through the Datadog web UI to ensure all necessary OCI resources have been created and configured properly.
    #
    # @param body [CreateTenancyConfigRequest] 
    # @param opts [Hash] the optional parameters
    # @return [Array<(TenancyConfig, Integer, Hash)>] TenancyConfig data, response status code and response headers
    def create_tenancy_config_with_http_info(body, opts = {})
      unstable_enabled = @api_client.config.unstable_operations["v2.create_tenancy_config".to_sym]
      if unstable_enabled
        @api_client.config.logger.warn format("Using unstable operation '%s'", "v2.create_tenancy_config")
      else
        raise DatadogAPIClient::APIError.new(message: format("Unstable operation '%s' is disabled", "v2.create_tenancy_config"))
      end

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OCIIntegrationAPI.create_tenancy_config ...'
      end
      # verify the required parameter 'body' is set
      if @api_client.config.client_side_validation && body.nil?
        fail ArgumentError, "Missing the required parameter 'body' when calling OCIIntegrationAPI.create_tenancy_config"
      end
      # resource path
      local_var_path = '/api/v2/integration/oci/tenancies'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(body)

      # return_type
      return_type = opts[:debug_return_type] || 'TenancyConfig'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :create_tenancy_config,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Post, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OCIIntegrationAPI#create_tenancy_config\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete tenancy config.
    #
    # @see #delete_tenancy_config_with_http_info
    def delete_tenancy_config(tenancy_ocid, opts = {})
      delete_tenancy_config_with_http_info(tenancy_ocid, opts)
      nil
    end

    # Delete tenancy config.
    #
    # Delete an existing tenancy config. This will stop all data collection from the specified OCI tenancy and remove the stored configuration. This operation cannot be undone.
    #
    # @param tenancy_ocid [String] The OCID of the tenancy config to delete.
    # @param opts [Hash] the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def delete_tenancy_config_with_http_info(tenancy_ocid, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OCIIntegrationAPI.delete_tenancy_config ...'
      end
      # verify the required parameter 'tenancy_ocid' is set
      if @api_client.config.client_side_validation && tenancy_ocid.nil?
        fail ArgumentError, "Missing the required parameter 'tenancy_ocid' when calling OCIIntegrationAPI.delete_tenancy_config"
      end
      # resource path
      local_var_path = '/api/v2/integration/oci/tenancies/{tenancy_ocid}'.sub('{tenancy_ocid}', CGI.escape(tenancy_ocid.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :delete_tenancy_config,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Delete, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OCIIntegrationAPI#delete_tenancy_config\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get tenancy config.
    #
    # @see #get_tenancy_config_with_http_info
    def get_tenancy_config(tenancy_ocid, opts = {})
      data, _status_code, _headers = get_tenancy_config_with_http_info(tenancy_ocid, opts)
      data
    end

    # Get tenancy config.
    #
    # Get a single tenancy config object by its OCID. Returns detailed configuration including authentication credentials, enabled services, region settings, and collection preferences.
    #
    # @param tenancy_ocid [String] The OCID of the tenancy config to retrieve.
    # @param opts [Hash] the optional parameters
    # @return [Array<(TenancyConfig, Integer, Hash)>] TenancyConfig data, response status code and response headers
    def get_tenancy_config_with_http_info(tenancy_ocid, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OCIIntegrationAPI.get_tenancy_config ...'
      end
      # verify the required parameter 'tenancy_ocid' is set
      if @api_client.config.client_side_validation && tenancy_ocid.nil?
        fail ArgumentError, "Missing the required parameter 'tenancy_ocid' when calling OCIIntegrationAPI.get_tenancy_config"
      end
      # resource path
      local_var_path = '/api/v2/integration/oci/tenancies/{tenancy_ocid}'.sub('{tenancy_ocid}', CGI.escape(tenancy_ocid.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'TenancyConfig'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :get_tenancy_config,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Get, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OCIIntegrationAPI#get_tenancy_config\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get tenancy configs.
    #
    # @see #get_tenancy_configs_with_http_info
    def get_tenancy_configs(opts = {})
      data, _status_code, _headers = get_tenancy_configs_with_http_info(opts)
      data
    end

    # Get tenancy configs.
    #
    # Get a list of all configured OCI tenancy integrations. Returns basic information about each tenancy including authentication credentials, region settings, and collection preferences for metrics, logs, and resources.
    #
    # @param opts [Hash] the optional parameters
    # @return [Array<(TenancyConfigList, Integer, Hash)>] TenancyConfigList data, response status code and response headers
    def get_tenancy_configs_with_http_info(opts = {})
      unstable_enabled = @api_client.config.unstable_operations["v2.get_tenancy_configs".to_sym]
      if unstable_enabled
        @api_client.config.logger.warn format("Using unstable operation '%s'", "v2.get_tenancy_configs")
      else
        raise DatadogAPIClient::APIError.new(message: format("Unstable operation '%s' is disabled", "v2.get_tenancy_configs"))
      end

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OCIIntegrationAPI.get_tenancy_configs ...'
      end
      # resource path
      local_var_path = '/api/v2/integration/oci/tenancies'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'TenancyConfigList'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :get_tenancy_configs,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Get, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OCIIntegrationAPI#get_tenancy_configs\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List tenancy products.
    #
    # @see #list_tenancy_products_with_http_info
    def list_tenancy_products(product_keys, opts = {})
      data, _status_code, _headers = list_tenancy_products_with_http_info(product_keys, opts)
      data
    end

    # List tenancy products.
    #
    # Lists the products for a given tenancy. Returns the enabled/disabled status of Datadog products (such as Cloud Security Posture Management) for specific OCI tenancies.
    #
    # @param product_keys [String] Comma-separated list of product keys to filter by.
    # @param opts [Hash] the optional parameters
    # @return [Array<(TenancyProductsList, Integer, Hash)>] TenancyProductsList data, response status code and response headers
    def list_tenancy_products_with_http_info(product_keys, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OCIIntegrationAPI.list_tenancy_products ...'
      end
      # verify the required parameter 'product_keys' is set
      if @api_client.config.client_side_validation && product_keys.nil?
        fail ArgumentError, "Missing the required parameter 'product_keys' when calling OCIIntegrationAPI.list_tenancy_products"
      end
      # resource path
      local_var_path = '/api/v2/integration/oci/products'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'productKeys'] = product_keys

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'TenancyProductsList'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :list_tenancy_products,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Get, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OCIIntegrationAPI#list_tenancy_products\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update tenancy config.
    #
    # @see #update_tenancy_config_with_http_info
    def update_tenancy_config(tenancy_ocid, body, opts = {})
      data, _status_code, _headers = update_tenancy_config_with_http_info(tenancy_ocid, body, opts)
      data
    end

    # Update tenancy config.
    #
    # Update an existing tenancy config. You can modify authentication credentials, enable/disable collection types, update service filters, and change region settings. Warning: We recommend using the Datadog web UI to avoid unintended update effects.
    #
    # @param tenancy_ocid [String] The OCID of the tenancy config to update.
    # @param body [UpdateTenancyConfigRequest] 
    # @param opts [Hash] the optional parameters
    # @return [Array<(TenancyConfig, Integer, Hash)>] TenancyConfig data, response status code and response headers
    def update_tenancy_config_with_http_info(tenancy_ocid, body, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OCIIntegrationAPI.update_tenancy_config ...'
      end
      # verify the required parameter 'tenancy_ocid' is set
      if @api_client.config.client_side_validation && tenancy_ocid.nil?
        fail ArgumentError, "Missing the required parameter 'tenancy_ocid' when calling OCIIntegrationAPI.update_tenancy_config"
      end
      # verify the required parameter 'body' is set
      if @api_client.config.client_side_validation && body.nil?
        fail ArgumentError, "Missing the required parameter 'body' when calling OCIIntegrationAPI.update_tenancy_config"
      end
      # resource path
      local_var_path = '/api/v2/integration/oci/tenancies/{tenancy_ocid}'.sub('{tenancy_ocid}', CGI.escape(tenancy_ocid.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(body)

      # return_type
      return_type = opts[:debug_return_type] || 'TenancyConfig'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :update_tenancy_config,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Patch, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OCIIntegrationAPI#update_tenancy_config\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
