=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'cgi'

module DatadogAPIClient::V2
  class RumReplayHeatmapsAPI
    attr_accessor :api_client

    def initialize(api_client = DatadogAPIClient::APIClient.default)
      @api_client = api_client
    end

    # Create replay heatmap snapshot.
    #
    # @see #create_replay_heatmap_snapshot_with_http_info
    def create_replay_heatmap_snapshot(body, opts = {})
      data, _status_code, _headers = create_replay_heatmap_snapshot_with_http_info(body, opts)
      data
    end

    # Create replay heatmap snapshot.
    #
    # Create a heatmap snapshot.
    #
    # @param body [SnapshotCreateRequest] 
    # @param opts [Hash] the optional parameters
    # @return [Array<(Snapshot, Integer, Hash)>] Snapshot data, response status code and response headers
    def create_replay_heatmap_snapshot_with_http_info(body, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RumReplayHeatmapsAPI.create_replay_heatmap_snapshot ...'
      end
      # verify the required parameter 'body' is set
      if @api_client.config.client_side_validation && body.nil?
        fail ArgumentError, "Missing the required parameter 'body' when calling RumReplayHeatmapsAPI.create_replay_heatmap_snapshot"
      end
      # resource path
      local_var_path = '/api/v2/replay/heatmap/snapshots'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(body)

      # return_type
      return_type = opts[:debug_return_type] || 'Snapshot'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth, :AuthZ]

      new_options = opts.merge(
        :operation => :create_replay_heatmap_snapshot,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Post, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RumReplayHeatmapsAPI#create_replay_heatmap_snapshot\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete replay heatmap snapshot.
    #
    # @see #delete_replay_heatmap_snapshot_with_http_info
    def delete_replay_heatmap_snapshot(snapshot_id, opts = {})
      delete_replay_heatmap_snapshot_with_http_info(snapshot_id, opts)
      nil
    end

    # Delete replay heatmap snapshot.
    #
    # Delete a heatmap snapshot.
    #
    # @param snapshot_id [String] Unique identifier of the heatmap snapshot.
    # @param opts [Hash] the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def delete_replay_heatmap_snapshot_with_http_info(snapshot_id, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RumReplayHeatmapsAPI.delete_replay_heatmap_snapshot ...'
      end
      # verify the required parameter 'snapshot_id' is set
      if @api_client.config.client_side_validation && snapshot_id.nil?
        fail ArgumentError, "Missing the required parameter 'snapshot_id' when calling RumReplayHeatmapsAPI.delete_replay_heatmap_snapshot"
      end
      # resource path
      local_var_path = '/api/v2/replay/heatmap/snapshots/{snapshot_id}'.sub('{snapshot_id}', CGI.escape(snapshot_id.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth, :AuthZ]

      new_options = opts.merge(
        :operation => :delete_replay_heatmap_snapshot,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Delete, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RumReplayHeatmapsAPI#delete_replay_heatmap_snapshot\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List replay heatmap snapshots.
    #
    # @see #list_replay_heatmap_snapshots_with_http_info
    def list_replay_heatmap_snapshots(filter_view_name, opts = {})
      data, _status_code, _headers = list_replay_heatmap_snapshots_with_http_info(filter_view_name, opts)
      data
    end

    # List replay heatmap snapshots.
    #
    # List heatmap snapshots.
    #
    # @param filter_view_name [String] View name to filter snapshots.
    # @param opts [Hash] the optional parameters
    # @option opts [String] :filter_device_type Device type to filter snapshots.
    # @option opts [Integer] :page_limit Maximum number of snapshots to return.
    # @option opts [String] :filter_application_id Filter by application ID.
    # @return [Array<(SnapshotArray, Integer, Hash)>] SnapshotArray data, response status code and response headers
    def list_replay_heatmap_snapshots_with_http_info(filter_view_name, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RumReplayHeatmapsAPI.list_replay_heatmap_snapshots ...'
      end
      # verify the required parameter 'filter_view_name' is set
      if @api_client.config.client_side_validation && filter_view_name.nil?
        fail ArgumentError, "Missing the required parameter 'filter_view_name' when calling RumReplayHeatmapsAPI.list_replay_heatmap_snapshots"
      end
      # resource path
      local_var_path = '/api/v2/replay/heatmap/snapshots'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'filter[view_name]'] = filter_view_name
      query_params[:'filter[device_type]'] = opts[:'filter_device_type'] if !opts[:'filter_device_type'].nil?
      query_params[:'page[limit]'] = opts[:'page_limit'] if !opts[:'page_limit'].nil?
      query_params[:'filter[application_id]'] = opts[:'filter_application_id'] if !opts[:'filter_application_id'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'SnapshotArray'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth, :AuthZ]

      new_options = opts.merge(
        :operation => :list_replay_heatmap_snapshots,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Get, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RumReplayHeatmapsAPI#list_replay_heatmap_snapshots\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update replay heatmap snapshot.
    #
    # @see #update_replay_heatmap_snapshot_with_http_info
    def update_replay_heatmap_snapshot(snapshot_id, body, opts = {})
      data, _status_code, _headers = update_replay_heatmap_snapshot_with_http_info(snapshot_id, body, opts)
      data
    end

    # Update replay heatmap snapshot.
    #
    # Update a heatmap snapshot.
    #
    # @param snapshot_id [String] Unique identifier of the heatmap snapshot.
    # @param body [SnapshotUpdateRequest] 
    # @param opts [Hash] the optional parameters
    # @return [Array<(Snapshot, Integer, Hash)>] Snapshot data, response status code and response headers
    def update_replay_heatmap_snapshot_with_http_info(snapshot_id, body, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RumReplayHeatmapsAPI.update_replay_heatmap_snapshot ...'
      end
      # verify the required parameter 'snapshot_id' is set
      if @api_client.config.client_side_validation && snapshot_id.nil?
        fail ArgumentError, "Missing the required parameter 'snapshot_id' when calling RumReplayHeatmapsAPI.update_replay_heatmap_snapshot"
      end
      # verify the required parameter 'body' is set
      if @api_client.config.client_side_validation && body.nil?
        fail ArgumentError, "Missing the required parameter 'body' when calling RumReplayHeatmapsAPI.update_replay_heatmap_snapshot"
      end
      # resource path
      local_var_path = '/api/v2/replay/heatmap/snapshots/{snapshot_id}'.sub('{snapshot_id}', CGI.escape(snapshot_id.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(body)

      # return_type
      return_type = opts[:debug_return_type] || 'Snapshot'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth, :AuthZ]

      new_options = opts.merge(
        :operation => :update_replay_heatmap_snapshot,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Patch, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RumReplayHeatmapsAPI#update_replay_heatmap_snapshot\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
