=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'cgi'

module DatadogAPIClient::V2
  class StegadographyAPI
    attr_accessor :api_client

    def initialize(api_client = DatadogAPIClient::APIClient.default)
      @api_client = api_client
    end

    # Get widgets from an image.
    #
    # @see #get_stegadography_widgets_with_http_info
    def get_stegadography_widgets(image, opts = {})
      data, _status_code, _headers = get_stegadography_widgets_with_http_info(image, opts)
      data
    end

    # Get widgets from an image.
    #
    # Extracts watermarks from a PNG image and returns the cached widget data
    # associated with each watermark found. The image must be uploaded as a
    # `multipart/form-data` request with the file in the `image` field.
    # Only widgets belonging to the authenticated organization are returned.
    #
    # @param image [File] PNG image file to scan for embedded watermarks.
    # @param opts [Hash] the optional parameters
    # @return [Array<(StegadographyGetWidgetsResponse, Integer, Hash)>] StegadographyGetWidgetsResponse data, response status code and response headers
    def get_stegadography_widgets_with_http_info(image, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: StegadographyAPI.get_stegadography_widgets ...'
      end
      # verify the required parameter 'image' is set
      if @api_client.config.client_side_validation && image.nil?
        fail ArgumentError, "Missing the required parameter 'image' when calling StegadographyAPI.get_stegadography_widgets"
      end
      # resource path
      local_var_path = '/api/v2/stegadography/get-widgets'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['multipart/form-data'])

      # form parameters
      form_params = opts[:form_params] || {}
      form_params['image'] = image

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'StegadographyGetWidgetsResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :get_stegadography_widgets,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Post, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: StegadographyAPI#get_stegadography_widgets\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
