=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # Attributes for updating an event email address.
  class EventEmailAddressUpdateAttributes
    include BaseGenericModel

    # The alert type of events generated from the email address.
    attr_reader :alert_type

    # A description of the event email address.
    attr_reader :description

    # A list of handles to notify when an email is received.
    attr_reader :notify_handles

    # A list of tags to apply to events generated from the email address.
    attr_reader :tags

    attr_accessor :additional_properties

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'alert_type' => :'alert_type',
        :'description' => :'description',
        :'notify_handles' => :'notify_handles',
        :'tags' => :'tags'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'alert_type' => :'EventEmailAddressAlertType',
        :'description' => :'String',
        :'notify_handles' => :'Array<String>',
        :'tags' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    # @!visibility private
    def self.openapi_nullable
      Set.new([
        :'description',
      ])
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V2::EventEmailAddressUpdateAttributes` initialize method"
      end

      self.additional_properties = {}
      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          self.additional_properties[k.to_sym] = v
        else
          h[k.to_sym] = v
        end
      }

      if attributes.key?(:'alert_type')
        self.alert_type = attributes[:'alert_type']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'notify_handles')
        if (value = attributes[:'notify_handles']).is_a?(Array)
          self.notify_handles = value
        end
      end

      if attributes.key?(:'tags')
        if (value = attributes[:'tags']).is_a?(Array)
          self.tags = value
        end
      end
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    # @!visibility private
    def valid?
      return false if @alert_type.nil?
      return false if @description.to_s.length > 1024
      return false if @notify_handles.nil?
      return false if @notify_handles.length > 10
      return false if @tags.nil?
      return false if @tags.length > 20
      true
    end

    # Custom attribute writer method with validation
    # @param alert_type [Object] Object to be assigned
    # @!visibility private
    def alert_type=(alert_type)
      if alert_type.nil?
        fail ArgumentError, 'invalid value for "alert_type", alert_type cannot be nil.'
      end
      @alert_type = alert_type
    end

    # Custom attribute writer method with validation
    # @param description [Object] Object to be assigned
    # @!visibility private
    def description=(description)
      if description.to_s.length > 1024
        fail ArgumentError, 'invalid value for "description", the character length must be smaller than or equal to 1024.'
      end
      @description = description
    end

    # Custom attribute writer method with validation
    # @param notify_handles [Object] Object to be assigned
    # @!visibility private
    def notify_handles=(notify_handles)
      if notify_handles.nil?
        fail ArgumentError, 'invalid value for "notify_handles", notify_handles cannot be nil.'
      end
      if notify_handles.length > 10
        fail ArgumentError, 'invalid value for "notify_handles", number of items must be less than or equal to 10.'
      end
      @notify_handles = notify_handles
    end

    # Custom attribute writer method with validation
    # @param tags [Object] Object to be assigned
    # @!visibility private
    def tags=(tags)
      if tags.nil?
        fail ArgumentError, 'invalid value for "tags", tags cannot be nil.'
      end
      if tags.length > 20
        fail ArgumentError, 'invalid value for "tags", number of items must be less than or equal to 20.'
      end
      @tags = tags
    end

    # Returns the object in the form of hash, with additionalProperties support.
    # @return [Hash] Returns the object in the form of hash
    # @!visibility private
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      self.additional_properties.each_pair do |attr, value|
        hash[attr] = value
      end
      hash
    end

    # Checks equality by comparing each attribute.
    # @param o [Object] Object to be compared
    # @!visibility private
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          alert_type == o.alert_type &&
          description == o.description &&
          notify_handles == o.notify_handles &&
          tags == o.tags &&
          additional_properties == o.additional_properties
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    # @!visibility private
    def hash
      [alert_type, description, notify_handles, tags, additional_properties].hash
    end
  end
end
