=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # Environment-specific settings for a feature flag.
  class FeatureFlagEnvironment
    include BaseGenericModel

    # Allocation metadata for this environment.
    attr_accessor :allocations

    # The allocation key used for the default variant.
    attr_accessor :default_allocation_key

    # The ID of the default variant for this environment.
    attr_accessor :default_variant_id

    # The ID of the environment.
    attr_reader :environment_id

    # The name of the environment.
    attr_accessor :environment_name

    # Indicates whether the environment is production.
    attr_accessor :is_production

    # The allocation key used for the override variant.
    attr_accessor :override_allocation_key

    # The ID of the override variant for this environment.
    attr_accessor :override_variant_id

    # Pending suggestion identifier, if approval is required.
    attr_accessor :pending_suggestion_id

    # Indicates whether feature flag changes require approval in this environment.
    attr_accessor :require_feature_flag_approval

    # Rollout percentage for this environment.
    attr_reader :rollout_percentage

    # Environment targeting rules for this feature flag.
    attr_accessor :rules

    # The status of a feature flag in an environment.
    attr_reader :status

    attr_accessor :additional_properties

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'allocations' => :'allocations',
        :'default_allocation_key' => :'default_allocation_key',
        :'default_variant_id' => :'default_variant_id',
        :'environment_id' => :'environment_id',
        :'environment_name' => :'environment_name',
        :'is_production' => :'is_production',
        :'override_allocation_key' => :'override_allocation_key',
        :'override_variant_id' => :'override_variant_id',
        :'pending_suggestion_id' => :'pending_suggestion_id',
        :'require_feature_flag_approval' => :'require_feature_flag_approval',
        :'rollout_percentage' => :'rollout_percentage',
        :'rules' => :'rules',
        :'status' => :'status'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'allocations' => :'Hash<String, Object>',
        :'default_allocation_key' => :'String',
        :'default_variant_id' => :'String',
        :'environment_id' => :'UUID',
        :'environment_name' => :'String',
        :'is_production' => :'Boolean',
        :'override_allocation_key' => :'String',
        :'override_variant_id' => :'String',
        :'pending_suggestion_id' => :'String',
        :'require_feature_flag_approval' => :'Boolean',
        :'rollout_percentage' => :'Integer',
        :'rules' => :'Array<Hash<String, Object>>',
        :'status' => :'FeatureFlagStatus'
      }
    end

    # List of attributes with nullable: true
    # @!visibility private
    def self.openapi_nullable
      Set.new([
        :'allocations',
        :'default_variant_id',
        :'override_variant_id',
        :'pending_suggestion_id',
      ])
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V2::FeatureFlagEnvironment` initialize method"
      end

      self.additional_properties = {}
      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          self.additional_properties[k.to_sym] = v
        else
          h[k.to_sym] = v
        end
      }

      if attributes.key?(:'allocations')
        self.allocations = attributes[:'allocations']
      end

      if attributes.key?(:'default_allocation_key')
        self.default_allocation_key = attributes[:'default_allocation_key']
      end

      if attributes.key?(:'default_variant_id')
        self.default_variant_id = attributes[:'default_variant_id']
      end

      if attributes.key?(:'environment_id')
        self.environment_id = attributes[:'environment_id']
      end

      if attributes.key?(:'environment_name')
        self.environment_name = attributes[:'environment_name']
      end

      if attributes.key?(:'is_production')
        self.is_production = attributes[:'is_production']
      end

      if attributes.key?(:'override_allocation_key')
        self.override_allocation_key = attributes[:'override_allocation_key']
      end

      if attributes.key?(:'override_variant_id')
        self.override_variant_id = attributes[:'override_variant_id']
      end

      if attributes.key?(:'pending_suggestion_id')
        self.pending_suggestion_id = attributes[:'pending_suggestion_id']
      end

      if attributes.key?(:'require_feature_flag_approval')
        self.require_feature_flag_approval = attributes[:'require_feature_flag_approval']
      end

      if attributes.key?(:'rollout_percentage')
        self.rollout_percentage = attributes[:'rollout_percentage']
      end

      if attributes.key?(:'rules')
        if (value = attributes[:'rules']).is_a?(Array)
          self.rules = value
        end
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    # @!visibility private
    def valid?
      return false if @environment_id.nil?
      return false if !@rollout_percentage.nil? && @rollout_percentage > 100
      return false if !@rollout_percentage.nil? && @rollout_percentage < 0
      return false if @status.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param environment_id [Object] Object to be assigned
    # @!visibility private
    def environment_id=(environment_id)
      if environment_id.nil?
        fail ArgumentError, 'invalid value for "environment_id", environment_id cannot be nil.'
      end
      @environment_id = environment_id
    end

    # Custom attribute writer method with validation
    # @param rollout_percentage [Object] Object to be assigned
    # @!visibility private
    def rollout_percentage=(rollout_percentage)
      if !rollout_percentage.nil? && rollout_percentage > 100
        fail ArgumentError, 'invalid value for "rollout_percentage", must be smaller than or equal to 100.'
      end
      if !rollout_percentage.nil? && rollout_percentage < 0
        fail ArgumentError, 'invalid value for "rollout_percentage", must be greater than or equal to 0.'
      end
      @rollout_percentage = rollout_percentage
    end

    # Custom attribute writer method with validation
    # @param status [Object] Object to be assigned
    # @!visibility private
    def status=(status)
      if status.nil?
        fail ArgumentError, 'invalid value for "status", status cannot be nil.'
      end
      @status = status
    end

    # Returns the object in the form of hash, with additionalProperties support.
    # @return [Hash] Returns the object in the form of hash
    # @!visibility private
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      self.additional_properties.each_pair do |attr, value|
        hash[attr] = value
      end
      hash
    end

    # Checks equality by comparing each attribute.
    # @param o [Object] Object to be compared
    # @!visibility private
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          allocations == o.allocations &&
          default_allocation_key == o.default_allocation_key &&
          default_variant_id == o.default_variant_id &&
          environment_id == o.environment_id &&
          environment_name == o.environment_name &&
          is_production == o.is_production &&
          override_allocation_key == o.override_allocation_key &&
          override_variant_id == o.override_variant_id &&
          pending_suggestion_id == o.pending_suggestion_id &&
          require_feature_flag_approval == o.require_feature_flag_approval &&
          rollout_percentage == o.rollout_percentage &&
          rules == o.rules &&
          status == o.status &&
          additional_properties == o.additional_properties
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    # @!visibility private
    def hash
      [allocations, default_allocation_key, default_variant_id, environment_id, environment_name, is_production, override_allocation_key, override_variant_id, pending_suggestion_id, require_feature_flag_approval, rollout_percentage, rules, status, additional_properties].hash
    end
  end
end
