=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # Attributes of the inbox rule
  class InboxRuleAttributes
    include BaseGenericModel

    # Action of the inbox rule
    attr_reader :action

    # Date as Unix timestamp in milliseconds
    attr_reader :created_at

    # User creating or modifying a rule
    attr_reader :created_by

    # Field used to enable or disable the rule.
    attr_reader :enabled

    # Date as Unix timestamp in milliseconds
    attr_reader :modified_at

    # User creating or modifying a rule
    attr_reader :modified_by

    # Name of the pipeline rule
    attr_reader :name

    # The definition of an automation pipeline rule scope.
    # A rule can act on specific issue types, security rule types, security rule IDs, rule severities, or a query.
    # The query can be used to filter resources on tags and attributes.
    # The issue type and rule types fields are required.
    attr_reader :rule

    attr_accessor :additional_properties

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'action' => :'action',
        :'created_at' => :'created_at',
        :'created_by' => :'created_by',
        :'enabled' => :'enabled',
        :'modified_at' => :'modified_at',
        :'modified_by' => :'modified_by',
        :'name' => :'name',
        :'rule' => :'rule'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'action' => :'ActionInbox',
        :'created_at' => :'Integer',
        :'created_by' => :'RuleUser',
        :'enabled' => :'Boolean',
        :'modified_at' => :'Integer',
        :'modified_by' => :'RuleUser',
        :'name' => :'String',
        :'rule' => :'Rule'
      }
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V2::InboxRuleAttributes` initialize method"
      end

      self.additional_properties = {}
      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          self.additional_properties[k.to_sym] = v
        else
          h[k.to_sym] = v
        end
      }

      if attributes.key?(:'action')
        self.action = attributes[:'action']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'created_by')
        self.created_by = attributes[:'created_by']
      end

      if attributes.key?(:'enabled')
        self.enabled = attributes[:'enabled']
      end

      if attributes.key?(:'modified_at')
        self.modified_at = attributes[:'modified_at']
      end

      if attributes.key?(:'modified_by')
        self.modified_by = attributes[:'modified_by']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'rule')
        self.rule = attributes[:'rule']
      end
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    # @!visibility private
    def valid?
      return false if @action.nil?
      return false if @created_at.nil?
      return false if @created_by.nil?
      return false if @enabled.nil?
      return false if @modified_at.nil?
      return false if @modified_by.nil?
      return false if @name.nil?
      return false if @rule.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param action [Object] Object to be assigned
    # @!visibility private
    def action=(action)
      if action.nil?
        fail ArgumentError, 'invalid value for "action", action cannot be nil.'
      end
      @action = action
    end

    # Custom attribute writer method with validation
    # @param created_at [Object] Object to be assigned
    # @!visibility private
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'invalid value for "created_at", created_at cannot be nil.'
      end
      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param created_by [Object] Object to be assigned
    # @!visibility private
    def created_by=(created_by)
      if created_by.nil?
        fail ArgumentError, 'invalid value for "created_by", created_by cannot be nil.'
      end
      @created_by = created_by
    end

    # Custom attribute writer method with validation
    # @param enabled [Object] Object to be assigned
    # @!visibility private
    def enabled=(enabled)
      if enabled.nil?
        fail ArgumentError, 'invalid value for "enabled", enabled cannot be nil.'
      end
      @enabled = enabled
    end

    # Custom attribute writer method with validation
    # @param modified_at [Object] Object to be assigned
    # @!visibility private
    def modified_at=(modified_at)
      if modified_at.nil?
        fail ArgumentError, 'invalid value for "modified_at", modified_at cannot be nil.'
      end
      @modified_at = modified_at
    end

    # Custom attribute writer method with validation
    # @param modified_by [Object] Object to be assigned
    # @!visibility private
    def modified_by=(modified_by)
      if modified_by.nil?
        fail ArgumentError, 'invalid value for "modified_by", modified_by cannot be nil.'
      end
      @modified_by = modified_by
    end

    # Custom attribute writer method with validation
    # @param name [Object] Object to be assigned
    # @!visibility private
    def name=(name)
      if name.nil?
        fail ArgumentError, 'invalid value for "name", name cannot be nil.'
      end
      @name = name
    end

    # Custom attribute writer method with validation
    # @param rule [Object] Object to be assigned
    # @!visibility private
    def rule=(rule)
      if rule.nil?
        fail ArgumentError, 'invalid value for "rule", rule cannot be nil.'
      end
      @rule = rule
    end

    # Returns the object in the form of hash, with additionalProperties support.
    # @return [Hash] Returns the object in the form of hash
    # @!visibility private
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      self.additional_properties.each_pair do |attr, value|
        hash[attr] = value
      end
      hash
    end

    # Checks equality by comparing each attribute.
    # @param o [Object] Object to be compared
    # @!visibility private
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          action == o.action &&
          created_at == o.created_at &&
          created_by == o.created_by &&
          enabled == o.enabled &&
          modified_at == o.modified_at &&
          modified_by == o.modified_by &&
          name == o.name &&
          rule == o.rule &&
          additional_properties == o.additional_properties
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    # @!visibility private
    def hash
      [action, created_at, created_by, enabled, modified_at, modified_by, name, rule, additional_properties].hash
    end
  end
end
