=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # Attributes of a case link.
  class IncidentCaseLinkDataAttributes
    include BaseGenericModel

    # The entity identifier.
    attr_reader :entity_id

    # Whether this is a page link.
    attr_reader :is_page

    # The relationship type.
    attr_reader :relationship

    attr_accessor :additional_properties

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'entity_id' => :'entity_id',
        :'is_page' => :'is_page',
        :'relationship' => :'relationship'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'entity_id' => :'String',
        :'is_page' => :'Boolean',
        :'relationship' => :'String'
      }
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V2::IncidentCaseLinkDataAttributes` initialize method"
      end

      self.additional_properties = {}
      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          self.additional_properties[k.to_sym] = v
        else
          h[k.to_sym] = v
        end
      }

      if attributes.key?(:'entity_id')
        self.entity_id = attributes[:'entity_id']
      end

      if attributes.key?(:'is_page')
        self.is_page = attributes[:'is_page']
      end

      if attributes.key?(:'relationship')
        self.relationship = attributes[:'relationship']
      end
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    # @!visibility private
    def valid?
      return false if @entity_id.nil?
      return false if @is_page.nil?
      return false if @relationship.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param entity_id [Object] Object to be assigned
    # @!visibility private
    def entity_id=(entity_id)
      if entity_id.nil?
        fail ArgumentError, 'invalid value for "entity_id", entity_id cannot be nil.'
      end
      @entity_id = entity_id
    end

    # Custom attribute writer method with validation
    # @param is_page [Object] Object to be assigned
    # @!visibility private
    def is_page=(is_page)
      if is_page.nil?
        fail ArgumentError, 'invalid value for "is_page", is_page cannot be nil.'
      end
      @is_page = is_page
    end

    # Custom attribute writer method with validation
    # @param relationship [Object] Object to be assigned
    # @!visibility private
    def relationship=(relationship)
      if relationship.nil?
        fail ArgumentError, 'invalid value for "relationship", relationship cannot be nil.'
      end
      @relationship = relationship
    end

    # Returns the object in the form of hash, with additionalProperties support.
    # @return [Hash] Returns the object in the form of hash
    # @!visibility private
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      self.additional_properties.each_pair do |attr, value|
        hash[attr] = value
      end
      hash
    end

    # Checks equality by comparing each attribute.
    # @param o [Object] Object to be compared
    # @!visibility private
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          entity_id == o.entity_id &&
          is_page == o.is_page &&
          relationship == o.relationship &&
          additional_properties == o.additional_properties
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    # @!visibility private
    def hash
      [entity_id, is_page, relationship, additional_properties].hash
    end
  end
end
