=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # An annotated interaction returned by the cross-queue lookup, including the source queue metadata.
  class LLMObsAnnotatedInteractionByTraceItem
    include BaseGenericModel

    # List of annotations for this interaction.
    attr_reader :annotations

    # Upstream entity identifier (trace ID, session ID, or deterministic display_block ID).
    attr_reader :content_id

    # Timestamp when the interaction was added to the queue.
    attr_reader :created_at

    # List of content blocks that make up a `display_block` interaction.
    # Must contain at least one block.
    attr_reader :display_block

    # Unique identifier of the interaction.
    attr_reader :id

    # Timestamp when the interaction was last updated.
    attr_reader :modified_at

    # Identifier of the annotation queue this interaction belongs to.
    attr_reader :queue_id

    # Name of the annotation queue this interaction belongs to.
    attr_reader :queue_name

    # Type of an annotated interaction.
    attr_reader :type

    attr_accessor :additional_properties

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'annotations' => :'annotations',
        :'content_id' => :'content_id',
        :'created_at' => :'created_at',
        :'display_block' => :'display_block',
        :'id' => :'id',
        :'modified_at' => :'modified_at',
        :'queue_id' => :'queue_id',
        :'queue_name' => :'queue_name',
        :'type' => :'type'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'annotations' => :'Array<LLMObsAnnotationItem>',
        :'content_id' => :'String',
        :'created_at' => :'Time',
        :'display_block' => :'Array<LLMObsContentBlock>',
        :'id' => :'String',
        :'modified_at' => :'Time',
        :'queue_id' => :'String',
        :'queue_name' => :'String',
        :'type' => :'LLMObsAnyInteractionType'
      }
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V2::LLMObsAnnotatedInteractionByTraceItem` initialize method"
      end

      self.additional_properties = {}
      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          self.additional_properties[k.to_sym] = v
        else
          h[k.to_sym] = v
        end
      }

      if attributes.key?(:'annotations')
        if (value = attributes[:'annotations']).is_a?(Array)
          self.annotations = value
        end
      end

      if attributes.key?(:'content_id')
        self.content_id = attributes[:'content_id']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'display_block')
        if (value = attributes[:'display_block']).is_a?(Array)
          self.display_block = value
        end
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'modified_at')
        self.modified_at = attributes[:'modified_at']
      end

      if attributes.key?(:'queue_id')
        self.queue_id = attributes[:'queue_id']
      end

      if attributes.key?(:'queue_name')
        self.queue_name = attributes[:'queue_name']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    # @!visibility private
    def valid?
      return false if @annotations.nil?
      return false if @content_id.nil?
      return false if @created_at.nil?
      return false if !@display_block.nil? && @display_block.length < 1
      return false if @id.nil?
      return false if @modified_at.nil?
      return false if @queue_id.nil?
      return false if @queue_name.nil?
      return false if @type.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param annotations [Object] Object to be assigned
    # @!visibility private
    def annotations=(annotations)
      if annotations.nil?
        fail ArgumentError, 'invalid value for "annotations", annotations cannot be nil.'
      end
      @annotations = annotations
    end

    # Custom attribute writer method with validation
    # @param content_id [Object] Object to be assigned
    # @!visibility private
    def content_id=(content_id)
      if content_id.nil?
        fail ArgumentError, 'invalid value for "content_id", content_id cannot be nil.'
      end
      @content_id = content_id
    end

    # Custom attribute writer method with validation
    # @param created_at [Object] Object to be assigned
    # @!visibility private
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'invalid value for "created_at", created_at cannot be nil.'
      end
      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param display_block [Object] Object to be assigned
    # @!visibility private
    def display_block=(display_block)
      if !display_block.nil? && display_block.length < 1
        fail ArgumentError, 'invalid value for "display_block", number of items must be greater than or equal to 1.'
      end
      @display_block = display_block
    end

    # Custom attribute writer method with validation
    # @param id [Object] Object to be assigned
    # @!visibility private
    def id=(id)
      if id.nil?
        fail ArgumentError, 'invalid value for "id", id cannot be nil.'
      end
      @id = id
    end

    # Custom attribute writer method with validation
    # @param modified_at [Object] Object to be assigned
    # @!visibility private
    def modified_at=(modified_at)
      if modified_at.nil?
        fail ArgumentError, 'invalid value for "modified_at", modified_at cannot be nil.'
      end
      @modified_at = modified_at
    end

    # Custom attribute writer method with validation
    # @param queue_id [Object] Object to be assigned
    # @!visibility private
    def queue_id=(queue_id)
      if queue_id.nil?
        fail ArgumentError, 'invalid value for "queue_id", queue_id cannot be nil.'
      end
      @queue_id = queue_id
    end

    # Custom attribute writer method with validation
    # @param queue_name [Object] Object to be assigned
    # @!visibility private
    def queue_name=(queue_name)
      if queue_name.nil?
        fail ArgumentError, 'invalid value for "queue_name", queue_name cannot be nil.'
      end
      @queue_name = queue_name
    end

    # Custom attribute writer method with validation
    # @param type [Object] Object to be assigned
    # @!visibility private
    def type=(type)
      if type.nil?
        fail ArgumentError, 'invalid value for "type", type cannot be nil.'
      end
      @type = type
    end

    # Returns the object in the form of hash, with additionalProperties support.
    # @return [Hash] Returns the object in the form of hash
    # @!visibility private
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      self.additional_properties.each_pair do |attr, value|
        hash[attr] = value
      end
      hash
    end

    # Checks equality by comparing each attribute.
    # @param o [Object] Object to be compared
    # @!visibility private
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          annotations == o.annotations &&
          content_id == o.content_id &&
          created_at == o.created_at &&
          display_block == o.display_block &&
          id == o.id &&
          modified_at == o.modified_at &&
          queue_id == o.queue_id &&
          queue_name == o.queue_name &&
          type == o.type &&
          additional_properties == o.additional_properties
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    # @!visibility private
    def hash
      [annotations, content_id, created_at, display_block, id, modified_at, queue_id, queue_name, type, additional_properties].hash
    end
  end
end
