=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # A topic discovered by an LLM Observability patterns run.
  class LLMObsPatternsTopic
    include BaseGenericModel

    # Timestamp when the topic was created.
    attr_reader :created_at

    # Description of the topic.
    attr_reader :description

    # Timestamp when the topic was first seen.
    attr_reader :first_seen_at

    # Level of the topic in the hierarchy. Level 0 is a leaf topic.
    attr_reader :hierarchy_level

    # Unique identifier of the topic.
    attr_reader :id

    # Whether the topic has been validated.
    attr_reader :is_validated

    # Name of the topic.
    attr_reader :name

    # Identifier of the parent topic. Empty for top-level topics.
    attr_reader :parent_topic_id

    # Number of data points assigned to the topic.
    attr_reader :point_count

    # Identifier of the run that produced the topic.
    attr_reader :run_id

    attr_accessor :additional_properties

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'created_at' => :'created_at',
        :'description' => :'description',
        :'first_seen_at' => :'first_seen_at',
        :'hierarchy_level' => :'hierarchy_level',
        :'id' => :'id',
        :'is_validated' => :'is_validated',
        :'name' => :'name',
        :'parent_topic_id' => :'parent_topic_id',
        :'point_count' => :'point_count',
        :'run_id' => :'run_id'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'created_at' => :'Time',
        :'description' => :'String',
        :'first_seen_at' => :'Time',
        :'hierarchy_level' => :'Integer',
        :'id' => :'String',
        :'is_validated' => :'Boolean',
        :'name' => :'String',
        :'parent_topic_id' => :'String',
        :'point_count' => :'Integer',
        :'run_id' => :'String'
      }
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V2::LLMObsPatternsTopic` initialize method"
      end

      self.additional_properties = {}
      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          self.additional_properties[k.to_sym] = v
        else
          h[k.to_sym] = v
        end
      }

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'first_seen_at')
        self.first_seen_at = attributes[:'first_seen_at']
      end

      if attributes.key?(:'hierarchy_level')
        self.hierarchy_level = attributes[:'hierarchy_level']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'is_validated')
        self.is_validated = attributes[:'is_validated']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'parent_topic_id')
        self.parent_topic_id = attributes[:'parent_topic_id']
      end

      if attributes.key?(:'point_count')
        self.point_count = attributes[:'point_count']
      end

      if attributes.key?(:'run_id')
        self.run_id = attributes[:'run_id']
      end
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    # @!visibility private
    def valid?
      return false if @created_at.nil?
      return false if @description.nil?
      return false if @first_seen_at.nil?
      return false if @hierarchy_level.nil?
      return false if @id.nil?
      return false if @is_validated.nil?
      return false if @name.nil?
      return false if @parent_topic_id.nil?
      return false if @point_count.nil?
      return false if @run_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param created_at [Object] Object to be assigned
    # @!visibility private
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'invalid value for "created_at", created_at cannot be nil.'
      end
      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param description [Object] Object to be assigned
    # @!visibility private
    def description=(description)
      if description.nil?
        fail ArgumentError, 'invalid value for "description", description cannot be nil.'
      end
      @description = description
    end

    # Custom attribute writer method with validation
    # @param first_seen_at [Object] Object to be assigned
    # @!visibility private
    def first_seen_at=(first_seen_at)
      if first_seen_at.nil?
        fail ArgumentError, 'invalid value for "first_seen_at", first_seen_at cannot be nil.'
      end
      @first_seen_at = first_seen_at
    end

    # Custom attribute writer method with validation
    # @param hierarchy_level [Object] Object to be assigned
    # @!visibility private
    def hierarchy_level=(hierarchy_level)
      if hierarchy_level.nil?
        fail ArgumentError, 'invalid value for "hierarchy_level", hierarchy_level cannot be nil.'
      end
      @hierarchy_level = hierarchy_level
    end

    # Custom attribute writer method with validation
    # @param id [Object] Object to be assigned
    # @!visibility private
    def id=(id)
      if id.nil?
        fail ArgumentError, 'invalid value for "id", id cannot be nil.'
      end
      @id = id
    end

    # Custom attribute writer method with validation
    # @param is_validated [Object] Object to be assigned
    # @!visibility private
    def is_validated=(is_validated)
      if is_validated.nil?
        fail ArgumentError, 'invalid value for "is_validated", is_validated cannot be nil.'
      end
      @is_validated = is_validated
    end

    # Custom attribute writer method with validation
    # @param name [Object] Object to be assigned
    # @!visibility private
    def name=(name)
      if name.nil?
        fail ArgumentError, 'invalid value for "name", name cannot be nil.'
      end
      @name = name
    end

    # Custom attribute writer method with validation
    # @param parent_topic_id [Object] Object to be assigned
    # @!visibility private
    def parent_topic_id=(parent_topic_id)
      if parent_topic_id.nil?
        fail ArgumentError, 'invalid value for "parent_topic_id", parent_topic_id cannot be nil.'
      end
      @parent_topic_id = parent_topic_id
    end

    # Custom attribute writer method with validation
    # @param point_count [Object] Object to be assigned
    # @!visibility private
    def point_count=(point_count)
      if point_count.nil?
        fail ArgumentError, 'invalid value for "point_count", point_count cannot be nil.'
      end
      @point_count = point_count
    end

    # Custom attribute writer method with validation
    # @param run_id [Object] Object to be assigned
    # @!visibility private
    def run_id=(run_id)
      if run_id.nil?
        fail ArgumentError, 'invalid value for "run_id", run_id cannot be nil.'
      end
      @run_id = run_id
    end

    # Returns the object in the form of hash, with additionalProperties support.
    # @return [Hash] Returns the object in the form of hash
    # @!visibility private
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      self.additional_properties.each_pair do |attr, value|
        hash[attr] = value
      end
      hash
    end

    # Checks equality by comparing each attribute.
    # @param o [Object] Object to be compared
    # @!visibility private
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          created_at == o.created_at &&
          description == o.description &&
          first_seen_at == o.first_seen_at &&
          hierarchy_level == o.hierarchy_level &&
          id == o.id &&
          is_validated == o.is_validated &&
          name == o.name &&
          parent_topic_id == o.parent_topic_id &&
          point_count == o.point_count &&
          run_id == o.run_id &&
          additional_properties == o.additional_properties
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    # @!visibility private
    def hash
      [created_at, description, first_seen_at, hierarchy_level, id, is_validated, name, parent_topic_id, point_count, run_id, additional_properties].hash
    end
  end
end
