=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # The `sumo_logic` destination forwards logs to Sumo Logic.
  class ObservabilityPipelineSumoLogicDestination
    include BaseGenericModel

    # Configuration for buffer settings on destination components.
    attr_accessor :buffer

    # The output encoding format.
    attr_accessor :encoding

    # A list of custom headers to include in the request to Sumo Logic.
    attr_accessor :header_custom_fields

    # Optional override for the host name header.
    attr_accessor :header_host_name

    # Optional override for the source category header.
    attr_accessor :header_source_category

    # Optional override for the source name header.
    attr_accessor :header_source_name

    # The unique identifier for this component.
    attr_reader :id

    # A list of component IDs whose output is used as the `input` for this component.
    attr_reader :inputs

    # The destination type. The value should always be `sumo_logic`.
    attr_reader :type

    attr_accessor :additional_properties

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'buffer' => :'buffer',
        :'encoding' => :'encoding',
        :'header_custom_fields' => :'header_custom_fields',
        :'header_host_name' => :'header_host_name',
        :'header_source_category' => :'header_source_category',
        :'header_source_name' => :'header_source_name',
        :'id' => :'id',
        :'inputs' => :'inputs',
        :'type' => :'type'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'buffer' => :'ObservabilityPipelineBufferOptions',
        :'encoding' => :'ObservabilityPipelineSumoLogicDestinationEncoding',
        :'header_custom_fields' => :'Array<ObservabilityPipelineSumoLogicDestinationHeaderCustomFieldsItem>',
        :'header_host_name' => :'String',
        :'header_source_category' => :'String',
        :'header_source_name' => :'String',
        :'id' => :'String',
        :'inputs' => :'Array<String>',
        :'type' => :'ObservabilityPipelineSumoLogicDestinationType'
      }
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V2::ObservabilityPipelineSumoLogicDestination` initialize method"
      end

      self.additional_properties = {}
      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          self.additional_properties[k.to_sym] = v
        else
          h[k.to_sym] = v
        end
      }

      if attributes.key?(:'buffer')
        self.buffer = attributes[:'buffer']
      end

      if attributes.key?(:'encoding')
        self.encoding = attributes[:'encoding']
      end

      if attributes.key?(:'header_custom_fields')
        if (value = attributes[:'header_custom_fields']).is_a?(Array)
          self.header_custom_fields = value
        end
      end

      if attributes.key?(:'header_host_name')
        self.header_host_name = attributes[:'header_host_name']
      end

      if attributes.key?(:'header_source_category')
        self.header_source_category = attributes[:'header_source_category']
      end

      if attributes.key?(:'header_source_name')
        self.header_source_name = attributes[:'header_source_name']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'inputs')
        if (value = attributes[:'inputs']).is_a?(Array)
          self.inputs = value
        end
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    # @!visibility private
    def valid?
      return false if @id.nil?
      return false if @inputs.nil?
      return false if @type.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param id [Object] Object to be assigned
    # @!visibility private
    def id=(id)
      if id.nil?
        fail ArgumentError, 'invalid value for "id", id cannot be nil.'
      end
      @id = id
    end

    # Custom attribute writer method with validation
    # @param inputs [Object] Object to be assigned
    # @!visibility private
    def inputs=(inputs)
      if inputs.nil?
        fail ArgumentError, 'invalid value for "inputs", inputs cannot be nil.'
      end
      @inputs = inputs
    end

    # Custom attribute writer method with validation
    # @param type [Object] Object to be assigned
    # @!visibility private
    def type=(type)
      if type.nil?
        fail ArgumentError, 'invalid value for "type", type cannot be nil.'
      end
      @type = type
    end

    # Returns the object in the form of hash, with additionalProperties support.
    # @return [Hash] Returns the object in the form of hash
    # @!visibility private
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      self.additional_properties.each_pair do |attr, value|
        hash[attr] = value
      end
      hash
    end

    # Checks equality by comparing each attribute.
    # @param o [Object] Object to be compared
    # @!visibility private
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          buffer == o.buffer &&
          encoding == o.encoding &&
          header_custom_fields == o.header_custom_fields &&
          header_host_name == o.header_host_name &&
          header_source_category == o.header_source_category &&
          header_source_name == o.header_source_name &&
          id == o.id &&
          inputs == o.inputs &&
          type == o.type &&
          additional_properties == o.additional_properties
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    # @!visibility private
    def hash
      [buffer, encoding, header_custom_fields, header_host_name, header_source_category, header_source_name, id, inputs, type, additional_properties].hash
    end
  end
end
