=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # Attributes for creating an enrollment.
  class OnPremManagementServiceEnrollmentAttributes
    include BaseGenericModel

    # List of allowed actions for the runner.
    attr_reader :actions_allowlist

    # The hostname for the runner. Required when push mode is enabled.
    attr_accessor :runner_host

    # The modes the runner should operate in.
    attr_reader :runner_modes

    # The name of the on-prem runner.
    attr_reader :runner_name

    attr_accessor :additional_properties

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'actions_allowlist' => :'actions_allowlist',
        :'runner_host' => :'runner_host',
        :'runner_modes' => :'runner_modes',
        :'runner_name' => :'runner_name'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'actions_allowlist' => :'Array<String>',
        :'runner_host' => :'String',
        :'runner_modes' => :'Array<OnPremManagementServiceEnrollmentAttributesRunnerModesItems>',
        :'runner_name' => :'String'
      }
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V2::OnPremManagementServiceEnrollmentAttributes` initialize method"
      end

      self.additional_properties = {}
      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          self.additional_properties[k.to_sym] = v
        else
          h[k.to_sym] = v
        end
      }

      if attributes.key?(:'actions_allowlist')
        if (value = attributes[:'actions_allowlist']).is_a?(Array)
          self.actions_allowlist = value
        end
      end

      if attributes.key?(:'runner_host')
        self.runner_host = attributes[:'runner_host']
      end

      if attributes.key?(:'runner_modes')
        if (value = attributes[:'runner_modes']).is_a?(Array)
          self.runner_modes = value
        end
      end

      if attributes.key?(:'runner_name')
        self.runner_name = attributes[:'runner_name']
      end
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    # @!visibility private
    def valid?
      return false if @actions_allowlist.nil?
      return false if @runner_modes.nil?
      return false if @runner_name.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param actions_allowlist [Object] Object to be assigned
    # @!visibility private
    def actions_allowlist=(actions_allowlist)
      if actions_allowlist.nil?
        fail ArgumentError, 'invalid value for "actions_allowlist", actions_allowlist cannot be nil.'
      end
      @actions_allowlist = actions_allowlist
    end

    # Custom attribute writer method with validation
    # @param runner_modes [Object] Object to be assigned
    # @!visibility private
    def runner_modes=(runner_modes)
      if runner_modes.nil?
        fail ArgumentError, 'invalid value for "runner_modes", runner_modes cannot be nil.'
      end
      @runner_modes = runner_modes
    end

    # Custom attribute writer method with validation
    # @param runner_name [Object] Object to be assigned
    # @!visibility private
    def runner_name=(runner_name)
      if runner_name.nil?
        fail ArgumentError, 'invalid value for "runner_name", runner_name cannot be nil.'
      end
      @runner_name = runner_name
    end

    # Returns the object in the form of hash, with additionalProperties support.
    # @return [Hash] Returns the object in the form of hash
    # @!visibility private
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      self.additional_properties.each_pair do |attr, value|
        hash[attr] = value
      end
      hash
    end

    # Checks equality by comparing each attribute.
    # @param o [Object] Object to be compared
    # @!visibility private
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          actions_allowlist == o.actions_allowlist &&
          runner_host == o.runner_host &&
          runner_modes == o.runner_modes &&
          runner_name == o.runner_name &&
          additional_properties == o.additional_properties
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    # @!visibility private
    def hash
      [actions_allowlist, runner_host, runner_modes, runner_name, additional_properties].hash
    end
  end
end
