=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # Attributes of an org group policy.
  class OrgGroupPolicyAttributes
    include BaseGenericModel

    # The policy content as key-value pairs.
    attr_accessor :content

    # The enforcement tier of the policy. `DEFAULT` means the policy is set but member orgs may mutate it. `ENFORCE` means the policy is strictly controlled and mutations are blocked for affected orgs. `DELEGATE` means each member org controls its own value.
    attr_reader :enforcement_tier

    # Timestamp when the policy was last modified.
    attr_reader :modified_at

    # The name of the policy.
    attr_reader :policy_name

    # The type of the policy. Only `org_config` is supported, indicating a policy backed by an organization configuration setting.
    attr_reader :policy_type

    attr_accessor :additional_properties

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'content' => :'content',
        :'enforcement_tier' => :'enforcement_tier',
        :'modified_at' => :'modified_at',
        :'policy_name' => :'policy_name',
        :'policy_type' => :'policy_type'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'content' => :'Hash<String, Object>',
        :'enforcement_tier' => :'OrgGroupPolicyEnforcementTier',
        :'modified_at' => :'Time',
        :'policy_name' => :'String',
        :'policy_type' => :'OrgGroupPolicyPolicyType'
      }
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V2::OrgGroupPolicyAttributes` initialize method"
      end

      self.additional_properties = {}
      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          self.additional_properties[k.to_sym] = v
        else
          h[k.to_sym] = v
        end
      }

      if attributes.key?(:'content')
        self.content = attributes[:'content']
      end

      if attributes.key?(:'enforcement_tier')
        self.enforcement_tier = attributes[:'enforcement_tier']
      end

      if attributes.key?(:'modified_at')
        self.modified_at = attributes[:'modified_at']
      end

      if attributes.key?(:'policy_name')
        self.policy_name = attributes[:'policy_name']
      end

      if attributes.key?(:'policy_type')
        self.policy_type = attributes[:'policy_type']
      end
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    # @!visibility private
    def valid?
      return false if @enforcement_tier.nil?
      return false if @modified_at.nil?
      return false if @policy_name.nil?
      return false if @policy_type.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param enforcement_tier [Object] Object to be assigned
    # @!visibility private
    def enforcement_tier=(enforcement_tier)
      if enforcement_tier.nil?
        fail ArgumentError, 'invalid value for "enforcement_tier", enforcement_tier cannot be nil.'
      end
      @enforcement_tier = enforcement_tier
    end

    # Custom attribute writer method with validation
    # @param modified_at [Object] Object to be assigned
    # @!visibility private
    def modified_at=(modified_at)
      if modified_at.nil?
        fail ArgumentError, 'invalid value for "modified_at", modified_at cannot be nil.'
      end
      @modified_at = modified_at
    end

    # Custom attribute writer method with validation
    # @param policy_name [Object] Object to be assigned
    # @!visibility private
    def policy_name=(policy_name)
      if policy_name.nil?
        fail ArgumentError, 'invalid value for "policy_name", policy_name cannot be nil.'
      end
      @policy_name = policy_name
    end

    # Custom attribute writer method with validation
    # @param policy_type [Object] Object to be assigned
    # @!visibility private
    def policy_type=(policy_type)
      if policy_type.nil?
        fail ArgumentError, 'invalid value for "policy_type", policy_type cannot be nil.'
      end
      @policy_type = policy_type
    end

    # Returns the object in the form of hash, with additionalProperties support.
    # @return [Hash] Returns the object in the form of hash
    # @!visibility private
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      self.additional_properties.each_pair do |attr, value|
        hash[attr] = value
      end
      hash
    end

    # Checks equality by comparing each attribute.
    # @param o [Object] Object to be compared
    # @!visibility private
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          content == o.content &&
          enforcement_tier == o.enforcement_tier &&
          modified_at == o.modified_at &&
          policy_name == o.policy_name &&
          policy_type == o.policy_type &&
          additional_properties == o.additional_properties
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    # @!visibility private
    def hash
      [content, enforcement_tier, modified_at, policy_name, policy_type, additional_properties].hash
    end
  end
end
