=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # The attributes of an ownership feedback request.
  class OwnershipFeedbackRequestAttributes
    include BaseGenericModel

    # The feedback action to apply to an inference.
    attr_reader :action

    # The handle of the actor submitting the feedback.
    attr_reader :actor_handle

    # The type of actor submitting the feedback, for example `user` or `service`.
    attr_reader :actor_type

    # The corrected owner handle. Required when `action` is `correct`.
    attr_accessor :corrected_owner_handle

    # The corrected owner type. Required when `action` is `correct`.
    attr_accessor :corrected_owner_type

    # The checksum of the inference being acted upon. Must match the current inference checksum or the request returns a conflict.
    attr_reader :inference_checksum

    # An optional free-form reason explaining the feedback.
    attr_accessor :reason

    attr_accessor :additional_properties

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'action' => :'action',
        :'actor_handle' => :'actor_handle',
        :'actor_type' => :'actor_type',
        :'corrected_owner_handle' => :'corrected_owner_handle',
        :'corrected_owner_type' => :'corrected_owner_type',
        :'inference_checksum' => :'inference_checksum',
        :'reason' => :'reason'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'action' => :'OwnershipFeedbackAction',
        :'actor_handle' => :'String',
        :'actor_type' => :'String',
        :'corrected_owner_handle' => :'String',
        :'corrected_owner_type' => :'String',
        :'inference_checksum' => :'String',
        :'reason' => :'String'
      }
    end

    # List of attributes with nullable: true
    # @!visibility private
    def self.openapi_nullable
      Set.new([
        :'corrected_owner_handle',
        :'corrected_owner_type',
        :'reason',
      ])
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V2::OwnershipFeedbackRequestAttributes` initialize method"
      end

      self.additional_properties = {}
      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          self.additional_properties[k.to_sym] = v
        else
          h[k.to_sym] = v
        end
      }

      if attributes.key?(:'action')
        self.action = attributes[:'action']
      end

      if attributes.key?(:'actor_handle')
        self.actor_handle = attributes[:'actor_handle']
      end

      if attributes.key?(:'actor_type')
        self.actor_type = attributes[:'actor_type']
      end

      if attributes.key?(:'corrected_owner_handle')
        self.corrected_owner_handle = attributes[:'corrected_owner_handle']
      end

      if attributes.key?(:'corrected_owner_type')
        self.corrected_owner_type = attributes[:'corrected_owner_type']
      end

      if attributes.key?(:'inference_checksum')
        self.inference_checksum = attributes[:'inference_checksum']
      end

      if attributes.key?(:'reason')
        self.reason = attributes[:'reason']
      end
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    # @!visibility private
    def valid?
      return false if @action.nil?
      return false if @actor_handle.nil?
      return false if @actor_type.nil?
      return false if @inference_checksum.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param action [Object] Object to be assigned
    # @!visibility private
    def action=(action)
      if action.nil?
        fail ArgumentError, 'invalid value for "action", action cannot be nil.'
      end
      @action = action
    end

    # Custom attribute writer method with validation
    # @param actor_handle [Object] Object to be assigned
    # @!visibility private
    def actor_handle=(actor_handle)
      if actor_handle.nil?
        fail ArgumentError, 'invalid value for "actor_handle", actor_handle cannot be nil.'
      end
      @actor_handle = actor_handle
    end

    # Custom attribute writer method with validation
    # @param actor_type [Object] Object to be assigned
    # @!visibility private
    def actor_type=(actor_type)
      if actor_type.nil?
        fail ArgumentError, 'invalid value for "actor_type", actor_type cannot be nil.'
      end
      @actor_type = actor_type
    end

    # Custom attribute writer method with validation
    # @param inference_checksum [Object] Object to be assigned
    # @!visibility private
    def inference_checksum=(inference_checksum)
      if inference_checksum.nil?
        fail ArgumentError, 'invalid value for "inference_checksum", inference_checksum cannot be nil.'
      end
      @inference_checksum = inference_checksum
    end

    # Returns the object in the form of hash, with additionalProperties support.
    # @return [Hash] Returns the object in the form of hash
    # @!visibility private
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      self.additional_properties.each_pair do |attr, value|
        hash[attr] = value
      end
      hash
    end

    # Checks equality by comparing each attribute.
    # @param o [Object] Object to be compared
    # @!visibility private
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          action == o.action &&
          actor_handle == o.actor_handle &&
          actor_type == o.actor_type &&
          corrected_owner_handle == o.corrected_owner_handle &&
          corrected_owner_type == o.corrected_owner_type &&
          inference_checksum == o.inference_checksum &&
          reason == o.reason &&
          additional_properties == o.additional_properties
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    # @!visibility private
    def hash
      [action, actor_handle, actor_type, corrected_owner_handle, corrected_owner_type, inference_checksum, reason, additional_properties].hash
    end
  end
end
