=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # Segments journey results by the values of a facet.
  class ProductAnalyticsGraphQueryGroupBy
    include BaseGenericModel

    # Attribute path to group by.
    attr_reader :facet

    # Maximum number of groups to return. Omit it to let the service choose.
    attr_reader :limit

    # Whether to exclude entities that have no value for this facet.
    attr_accessor :should_exclude_missing

    # Sort configuration for group-by results.
    attr_accessor :sort

    # Audience dimension to group by, instead of an event facet.
    attr_accessor :source

    # A reference to a step, or a range of steps, in the journey.
    # Use a `node` target to name a single step, or a `path` target to name the range
    # between two steps.
    attr_accessor :target

    # Restricts the results to these facet values.
    attr_accessor :value_filters

    attr_accessor :additional_properties

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'facet' => :'facet',
        :'limit' => :'limit',
        :'should_exclude_missing' => :'should_exclude_missing',
        :'sort' => :'sort',
        :'source' => :'source',
        :'target' => :'target',
        :'value_filters' => :'value_filters'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'facet' => :'String',
        :'limit' => :'Integer',
        :'should_exclude_missing' => :'Boolean',
        :'sort' => :'ProductAnalyticsGroupBySort',
        :'source' => :'ProductAnalyticsGraphQueryGroupBySource',
        :'target' => :'ProductAnalyticsJourneyTarget',
        :'value_filters' => :'Array<String>'
      }
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V2::ProductAnalyticsGraphQueryGroupBy` initialize method"
      end

      self.additional_properties = {}
      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          self.additional_properties[k.to_sym] = v
        else
          h[k.to_sym] = v
        end
      }

      if attributes.key?(:'facet')
        self.facet = attributes[:'facet']
      end

      if attributes.key?(:'limit')
        self.limit = attributes[:'limit']
      end

      if attributes.key?(:'should_exclude_missing')
        self.should_exclude_missing = attributes[:'should_exclude_missing']
      end

      if attributes.key?(:'sort')
        self.sort = attributes[:'sort']
      end

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      end

      if attributes.key?(:'target')
        self.target = attributes[:'target']
      end

      if attributes.key?(:'value_filters')
        if (value = attributes[:'value_filters']).is_a?(Array)
          self.value_filters = value
        end
      end
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    # @!visibility private
    def valid?
      return false if @facet.nil?
      return false if !@limit.nil? && @limit < 1
      true
    end

    # Custom attribute writer method with validation
    # @param facet [Object] Object to be assigned
    # @!visibility private
    def facet=(facet)
      if facet.nil?
        fail ArgumentError, 'invalid value for "facet", facet cannot be nil.'
      end
      @facet = facet
    end

    # Custom attribute writer method with validation
    # @param limit [Object] Object to be assigned
    # @!visibility private
    def limit=(limit)
      if !limit.nil? && limit < 1
        fail ArgumentError, 'invalid value for "limit", must be greater than or equal to 1.'
      end
      @limit = limit
    end

    # Returns the object in the form of hash, with additionalProperties support.
    # @return [Hash] Returns the object in the form of hash
    # @!visibility private
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      self.additional_properties.each_pair do |attr, value|
        hash[attr] = value
      end
      hash
    end

    # Checks equality by comparing each attribute.
    # @param o [Object] Object to be compared
    # @!visibility private
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          facet == o.facet &&
          limit == o.limit &&
          should_exclude_missing == o.should_exclude_missing &&
          sort == o.sort &&
          source == o.source &&
          target == o.target &&
          value_filters == o.value_filters &&
          additional_properties == o.additional_properties
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    # @!visibility private
    def hash
      [facet, limit, should_exclude_missing, sort, source, target, value_filters, additional_properties].hash
    end
  end
end
