=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # The sort parameters used for querying security monitoring rules.
  class SecurityMonitoringRuleSort
    include BaseEnumModel

    NAME = "name".freeze
    CREATION_DATE = "creation_date".freeze
    UPDATE_DATE = "update_date".freeze
    ENABLED = "enabled".freeze
    TYPE = "type".freeze
    HIGHEST_SEVERITY = "highest_severity".freeze
    SOURCE = "source".freeze
    NAME_DESCENDING = "-name".freeze
    CREATION_DATE_DESCENDING = "-creation_date".freeze
    UPDATE_DATE_DESCENDING = "-update_date".freeze
    ENABLED_DESCENDING = "-enabled".freeze
    TYPE_DESCENDING = "-type".freeze
    HIGHEST_SEVERITY_DESCENDING = "-highest_severity".freeze
    SOURCE_DESCENDING = "-source".freeze
  end
end
