=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # The attributes of a trace returned by the Get trace by ID endpoint.
  class TraceAttributes
    include BaseGenericModel

    # Indicates whether the trace was truncated because its size exceeded the maximum response payload.
    attr_reader :is_truncated

    # The list of spans that compose the trace.
    attr_reader :spans

    attr_accessor :additional_properties

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'is_truncated' => :'is_truncated',
        :'spans' => :'spans'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'is_truncated' => :'Boolean',
        :'spans' => :'Array<APMTraceSpan>'
      }
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V2::TraceAttributes` initialize method"
      end

      self.additional_properties = {}
      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          self.additional_properties[k.to_sym] = v
        else
          h[k.to_sym] = v
        end
      }

      if attributes.key?(:'is_truncated')
        self.is_truncated = attributes[:'is_truncated']
      end

      if attributes.key?(:'spans')
        if (value = attributes[:'spans']).is_a?(Array)
          self.spans = value
        end
      end
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    # @!visibility private
    def valid?
      return false if @is_truncated.nil?
      return false if @spans.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param is_truncated [Object] Object to be assigned
    # @!visibility private
    def is_truncated=(is_truncated)
      if is_truncated.nil?
        fail ArgumentError, 'invalid value for "is_truncated", is_truncated cannot be nil.'
      end
      @is_truncated = is_truncated
    end

    # Custom attribute writer method with validation
    # @param spans [Object] Object to be assigned
    # @!visibility private
    def spans=(spans)
      if spans.nil?
        fail ArgumentError, 'invalid value for "spans", spans cannot be nil.'
      end
      @spans = spans
    end

    # Returns the object in the form of hash, with additionalProperties support.
    # @return [Hash] Returns the object in the form of hash
    # @!visibility private
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      self.additional_properties.each_pair do |attr, value|
        hash[attr] = value
      end
      hash
    end

    # Checks equality by comparing each attribute.
    # @param o [Object] Object to be compared
    # @!visibility private
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          is_truncated == o.is_truncated &&
          spans == o.spans &&
          additional_properties == o.additional_properties
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    # @!visibility private
    def hash
      [is_truncated, spans, additional_properties].hash
    end
  end
end
