=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # Data Datadog collects from Twilio, keyed by dataflow id.
  class TwilioIntegrationDataflowsResponse
    include BaseGenericModel

    # Twilio Alert resource logs, which detail the errors and warnings raised when Twilio makes a webhook request to your server or when your application calls the Twilio REST API.
    attr_accessor :twilio_alerts_logs

    # Twilio Call Summary resource logs, covering the metadata and performance of the calls made from your Twilio account. Requires Voice Insights Advanced Features to be enabled on the Twilio account; without it this dataflow collects no data.
    attr_accessor :twilio_call_summaries_logs

    # Your Twilio cost data, so that Twilio spend can be broken down and attributed in [Cloud Cost Management](https://docs.datadoghq.com/cloud_cost_management/).
    attr_accessor :twilio_cloud_cost_metrics

    # Twilio Event resource logs, which record virtually every action taken in your Twilio account, such as provisioning a phone number, changing account security settings, or deleting a recording. Actions are recorded whether they came from the REST API, a user in the Twilio Console, or Twilio itself. [Cloud SIEM](https://docs.datadoghq.com/security/cloud_siem/) analyzes and correlates these logs to detect threats in real time.
    attr_accessor :twilio_events_logs

    # Twilio Message resource logs for inbound and outbound messages, used to track delivery and troubleshoot message errors. A log is produced when you send a message through the REST API, when Twilio executes a TwiML instruction, and when someone messages one of your Twilio numbers or channel addresses. Message bodies are never collected.
    attr_accessor :twilio_messages_logs

    attr_accessor :additional_properties

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'twilio_alerts_logs' => :'twilio-alerts-logs',
        :'twilio_call_summaries_logs' => :'twilio-call-summaries-logs',
        :'twilio_cloud_cost_metrics' => :'twilio-cloud-cost-metrics',
        :'twilio_events_logs' => :'twilio-events-logs',
        :'twilio_messages_logs' => :'twilio-messages-logs'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'twilio_alerts_logs' => :'TwilioAlertsLogsIntegrationDataflowResponse',
        :'twilio_call_summaries_logs' => :'TwilioCallSummariesLogsIntegrationDataflowResponse',
        :'twilio_cloud_cost_metrics' => :'TwilioCloudCostMetricsIntegrationDataflowResponse',
        :'twilio_events_logs' => :'TwilioEventsLogsIntegrationDataflowResponse',
        :'twilio_messages_logs' => :'TwilioMessagesLogsIntegrationDataflowResponse'
      }
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V2::TwilioIntegrationDataflowsResponse` initialize method"
      end

      self.additional_properties = {}
      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          self.additional_properties[k.to_sym] = v
        else
          h[k.to_sym] = v
        end
      }

      if attributes.key?(:'twilio_alerts_logs')
        self.twilio_alerts_logs = attributes[:'twilio_alerts_logs']
      end

      if attributes.key?(:'twilio_call_summaries_logs')
        self.twilio_call_summaries_logs = attributes[:'twilio_call_summaries_logs']
      end

      if attributes.key?(:'twilio_cloud_cost_metrics')
        self.twilio_cloud_cost_metrics = attributes[:'twilio_cloud_cost_metrics']
      end

      if attributes.key?(:'twilio_events_logs')
        self.twilio_events_logs = attributes[:'twilio_events_logs']
      end

      if attributes.key?(:'twilio_messages_logs')
        self.twilio_messages_logs = attributes[:'twilio_messages_logs']
      end
    end

    # Returns the object in the form of hash, with additionalProperties support.
    # @return [Hash] Returns the object in the form of hash
    # @!visibility private
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      self.additional_properties.each_pair do |attr, value|
        hash[attr] = value
      end
      hash
    end

    # Checks equality by comparing each attribute.
    # @param o [Object] Object to be compared
    # @!visibility private
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          twilio_alerts_logs == o.twilio_alerts_logs &&
          twilio_call_summaries_logs == o.twilio_call_summaries_logs &&
          twilio_cloud_cost_metrics == o.twilio_cloud_cost_metrics &&
          twilio_events_logs == o.twilio_events_logs &&
          twilio_messages_logs == o.twilio_messages_logs &&
          additional_properties == o.additional_properties
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    # @!visibility private
    def hash
      [twilio_alerts_logs, twilio_call_summaries_logs, twilio_cloud_cost_metrics, twilio_events_logs, twilio_messages_logs, additional_properties].hash
    end
  end
end
