http_interactions:
- recorded_at: Mon, 02 May 2022 16:40:49 GMT
  request:
    body: null
    headers:
      Accept:
      - application/json;datetime-format=rfc3339
    method: GET
    uri: https://api.datadoghq.com/api/v2/usage/application_security?start_hr=2022-04-29T16%3A40%3A49.302Z&end_hr=2022-04-27T16%3A40%3A49.302Z
  response:
    body:
      encoding: UTF-8
      string: '{"errors":["start_hr [YYYY-MM-DDThh] must be before end_hr [YYYY-MM-DDThh]"]}

        '
    headers:
      Content-Type:
      - application/json
    status:
      code: 400
      message: Bad Request
recorded_with: VCR 6.0.0
