http_interactions:
- recorded_at: Mon, 21 Aug 2023 19:44:48 GMT
  request:
    body: null
    headers:
      Accept:
      - application/json
    method: GET
    uri: https://api.datadoghq.com/api/v2/team/REPLACE.ME/permission-settings
  response:
    body:
      encoding: UTF-8
      string: '{"errors":["REPLACE.ME is not a valid UUID not found"]}'
    headers:
      Content-Type:
      - application/json
    status:
      code: 404
      message: Not Found
recorded_with: VCR 6.0.0
