=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://openapi-generator.tech

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'spec_helper'
require 'json'

# Unit tests for DatadogAPIClient::V1::WebhooksIntegrationAPI
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhooksIntegrationAPI' do
  before do
    # run before each test
    @api_instance = DatadogAPIClient::V1::WebhooksIntegrationAPI.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksIntegrationAPI' do
    it 'should create an instance of WebhooksIntegrationAPI' do
      expect(@api_instance).to be_instance_of(DatadogAPIClient::V1::WebhooksIntegrationAPI)
    end
  end

  # unit tests for create_webhooks_integration
  # Create a webhooks integration
  # Creates an endpoint with the name &#x60;&lt;WEBHOOK_NAME&gt;&#x60;.
  # @param body Create a webhooks integration request body.
  # @param [Hash] opts the optional parameters
  # @return [WebhooksIntegration]
  describe 'create_webhooks_integration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_webhooks_integration_custom_variable
  # Create a custom variable
  # Creates an endpoint with the name &#x60;&lt;CUSTOM_VARIABLE_NAME&gt;&#x60;.
  # @param body Define a custom variable request body.
  # @param [Hash] opts the optional parameters
  # @return [WebhooksIntegrationCustomVariableResponse]
  describe 'create_webhooks_integration_custom_variable test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_webhooks_integration
  # Delete a webhook
  # Deletes the endpoint with the name &#x60;&lt;WEBHOOK NAME&gt;&#x60;.
  # @param webhook_name The name of the webhook.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_webhooks_integration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_webhooks_integration_custom_variable
  # Delete a custom variable
  # Deletes the endpoint with the name &#x60;&lt;CUSTOM_VARIABLE_NAME&gt;&#x60;.
  # @param custom_variable_name The name of the custom variable.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_webhooks_integration_custom_variable test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_webhooks_integration
  # Get a webhook integration
  # Gets the content of the webhook with the name &#x60;&lt;WEBHOOK_NAME&gt;&#x60;.
  # @param webhook_name The name of the webhook.
  # @param [Hash] opts the optional parameters
  # @return [WebhooksIntegration]
  describe 'get_webhooks_integration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_webhooks_integration_custom_variable
  # Get a custom variable
  # Shows the content of the custom variable with the name &#x60;&lt;CUSTOM_VARIABLE_NAME&gt;&#x60;.  If the custom variable is secret, the value does not return in the response payload.
  # @param custom_variable_name The name of the custom variable.
  # @param [Hash] opts the optional parameters
  # @return [WebhooksIntegrationCustomVariableResponse]
  describe 'get_webhooks_integration_custom_variable test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_webhooks_integration
  # Update a webhook
  # Updates the endpoint with the name &#x60;&lt;WEBHOOK_NAME&gt;&#x60;.
  # @param webhook_name The name of the webhook.
  # @param body Update an existing Datadog-Webhooks integration.
  # @param [Hash] opts the optional parameters
  # @return [WebhooksIntegration]
  describe 'update_webhooks_integration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_webhooks_integration_custom_variable
  # Update a custom variable
  # Updates the endpoint with the name &#x60;&lt;CUSTOM_VARIABLE_NAME&gt;&#x60;.
  # @param custom_variable_name The name of the custom variable.
  # @param body Update an existing custom variable request body.
  # @param [Hash] opts the optional parameters
  # @return [WebhooksIntegrationCustomVariableResponse]
  describe 'update_webhooks_integration_custom_variable test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
