http_interactions:
- recorded_at: Mon, 23 Jun 2025 13:07:11 GMT
  request:
    body: null
    headers:
      Accept:
      - application/json
    method: GET
    uri: https://api.datadoghq.com/api/v2/cost/gcp_uc_config
  response:
    body:
      encoding: UTF-8
      string: '{"data":[]}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 200
      message: OK
recorded_with: VCR 6.0.0
