http_interactions:
- recorded_at: Thu, 16 Nov 2023 16:58:35 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"finished_at":1693491984000,"git":{"commit_sha":"66adc9350f2cc9b250b69abddab733dd55e1a588","repository_url":"https://github.com/organization/example-repository"},"service":"shopist","started_at":16934919740000,"version":"v1.12.07"}}}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
    method: POST
    uri: https://api.datadoghq.com/api/v2/dora/deployment
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"id":"2a47b5f25b160b8a","type":"dora_deployment"}}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 200
      message: OK
recorded_with: VCR 6.0.0
