=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # Color palette used by range-based conditional formatting rules.
  class GuidedTableRangePalette
    include BaseEnumModel

    TRANSPARENT_TO_GREEN = "transparent_to_green".freeze
    TRANSPARENT_TO_ORANGE = "transparent_to_orange".freeze
    TRANSPARENT_TO_RED = "transparent_to_red".freeze
    TRANSPARENT_TO_BLUE = "transparent_to_blue".freeze
    RED_TRANSPARENT_GREEN = "red_transparent_green".freeze
    RED_TRANSPARENT_BLUE = "red_transparent_blue".freeze
    VIVID_TRANSPARENT_TO_GREEN = "vivid_transparent_to_green".freeze
    VIVID_TRANSPARENT_TO_ORANGE = "vivid_transparent_to_orange".freeze
    VIVID_TRANSPARENT_TO_RED = "vivid_transparent_to_red".freeze
    VIVID_TRANSPARENT_TO_BLUE = "vivid_transparent_to_blue".freeze
    VIVID_RED_TRANSPARENT_GREEN = "vivid_red_transparent_green".freeze
    VIVID_RED_TRANSPARENT_BLUE = "vivid_red_transparent_blue".freeze
  end
end
