=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # A color and optional lower threshold for a discrete bin.
  class HeatgridColorBin
    include BaseGenericModel

    # A color string, or two color strings for the light and dark themes, in that order.
    attr_reader :color

    # Inclusive lower bound. Omit for the first bin.
    attr_accessor :lower_bound

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'color' => :'color',
        :'lower_bound' => :'lower_bound'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'color' => :'HeatgridColor',
        :'lower_bound' => :'Float'
      }
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V1::HeatgridColorBin` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DatadogAPIClient::V1::HeatgridColorBin`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'color')
        self.color = attributes[:'color']
      end

      if attributes.key?(:'lower_bound')
        self.lower_bound = attributes[:'lower_bound']
      end
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    # @!visibility private
    def valid?
      return false if @color.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param color [Object] Object to be assigned
    # @!visibility private
    def color=(color)
      if color.nil?
        fail ArgumentError, 'invalid value for "color", color cannot be nil.'
      end
      @color = color
    end

    # Checks equality by comparing each attribute.
    # @param o [Object] Object to be compared
    # @!visibility private
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          color == o.color &&
          lower_bound == o.lower_bound
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    # @!visibility private
    def hash
      [color, lower_bound].hash
    end
  end
end
