=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'

module DatadogAPIClient::V1
  class WidgetServiceSummaryDisplayFormat
    ONE_COLUMN = "one_column".freeze
    TWO_COLUMN = "two_column".freeze
    THREE_COLUMN = "three_column".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = WidgetServiceSummaryDisplayFormat.constants.select { |c| WidgetServiceSummaryDisplayFormat::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #WidgetServiceSummaryDisplayFormat" if constantValues.empty?
      value
    end
  end
end
