---
http_interactions:
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/roles
    body:
      encoding: UTF-8
      string: '{"data":{"type":"roles","attributes":{"name":"ruby-Create-role-returns-OK-response-1601469619"}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/0.1.0 (ruby 2.6.3; os darwin18.7.0; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 30 Sep 2020 12:40:19 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '415'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      Set-Cookie:
      - DD-PSHARD=233; Max-Age=604800; Path=/; expires=Wed, 07-Oct-2020 12:40:19 GMT;
        secure; HttpOnly
      X-Dd-Version:
      - '35.3116014'
      X-Ratelimit-Limit:
      - '500'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '41'
      X-Ratelimit-Remaining:
      - '497'
      X-Dd-Debug:
      - RCObiQ2dtM/JQUOdAbTQmIrpsZR5eT9bZEwE14hAfjq3x8DBTBCy/8ina/nQCRGE
      Dd-Pool:
      - dogweb
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"data":{"type":"roles","id":"1977e49e-031a-11eb-b513-2fb612486408","attributes":{"name":"ruby-Create-role-returns-OK-response-1601469619","created_at":"2020-09-30T12:40:19.624684+00:00","modified_at":"2020-09-30T12:40:19.624684+00:00"},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"}]}}}}'
  recorded_at: Wed, 30 Sep 2020 12:40:19 GMT
recorded_with: VCR 6.0.0
