---
http_interactions:
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/roles
    body:
      encoding: UTF-8
      string: '{"data":{"type":"roles","attributes":{"name":"ruby-Create-role-returns-OK-response-1599759323"}}}'
    headers:
      User-Agent:
      - OpenAPI-Generator/0.1.0/ruby
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 10 Sep 2020 17:35:24 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '415'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      Set-Cookie:
      - DD-PSHARD=233; Max-Age=604800; Path=/; expires=Thu, 17-Sep-2020 17:35:23 GMT;
        secure; HttpOnly
      X-Dd-Version:
      - '35.3014711'
      X-Ratelimit-Limit:
      - '500'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '37'
      X-Ratelimit-Remaining:
      - '497'
      X-Dd-Debug:
      - d31ebXSBBNIfMRbwTUSeNjY3IxejCQxGK8GB7MdTMNs7w40n94in+BXmkLo5BsFJ
      Dd-Pool:
      - dogweb
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"data":{"type":"roles","id":"01d5f4ea-f38c-11ea-ac35-ab3cdc044eea","attributes":{"name":"ruby-Create-role-returns-OK-response-1599759323","created_at":"2020-09-10T17:35:23.998431+00:00","modified_at":"2020-09-10T17:35:23.998431+00:00"},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"}]}}}}'
  recorded_at: Thu, 10 Sep 2020 17:35:23 GMT
recorded_with: VCR 6.0.0
