---
http_interactions:
- request:
    method: get
    uri: https://api.datadoghq.com/api/v2/roles?filter=ruby-List-roles-returns-OK-response-1601469618
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - datadog-api-client-ruby/0.1.0 (ruby 2.6.3; os darwin18.7.0; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 30 Sep 2020 12:40:19 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '492'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      Set-Cookie:
      - DD-PSHARD=233; Max-Age=604800; Path=/; expires=Wed, 07-Oct-2020 12:40:19 GMT;
        secure; HttpOnly
      X-Dd-Version:
      - '35.3116014'
      X-Ratelimit-Limit:
      - '500'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '41'
      X-Ratelimit-Remaining:
      - '498'
      X-Dd-Debug:
      - 2yLQyeuXdHKf2qhVlcnhVSRUgzA6Krta0LEltrGESIMHoX7HWgb/dSrVA+a76Sm3
      Dd-Pool:
      - dogweb
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"meta":{"page":{"total_filtered_count":1,"total_count":976}},"data":[{"type":"roles","id":"191a5ac2-031a-11eb-b513-6f4ff7bf95c1","attributes":{"name":"ruby-List-roles-returns-OK-response-1601469618","created_at":"2020-09-30T12:40:19.011972+00:00","modified_at":"2020-09-30T12:40:19.011972+00:00","user_count":0},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"}]}}}]}'
  recorded_at: Wed, 30 Sep 2020 12:40:18 GMT
- request:
    method: get
    uri: https://api.datadoghq.com/api/v2/roles?filter=ruby-List_roles_returns_OK_response-1601469618
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - datadog-api-client-ruby/0.1.0 (ruby 2.6.3; os darwin18.7.0; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 24 Nov 2020 14:43:57 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '912'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      Set-Cookie:
      - DD-PSHARD=233; Max-Age=604800; Path=/; expires=Tue, 01-Dec-2020 14:43:57 GMT;
        secure; HttpOnly
      X-Dd-Version:
      - '35.3424786'
      X-Ratelimit-Limit:
      - '500'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '3'
      X-Ratelimit-Remaining:
      - '498'
      X-Dd-Debug:
      - t3HUEZc5ir8lXNnqzkff2uqNehUi1czGcghjOPRgwaz4xZmG6O4HwEI6mdtgJV0i
      Dd-Pool:
      - dogweb
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"meta":{"page":{"total_filtered_count":2,"total_count":56}},"data":[{"type":"roles","id":"7b585e68-2e63-11eb-855e-dfa12daa8d2a","attributes":{"name":"ruby-List_roles_returns_OK_response-1601469618","created_at":"2020-11-24T14:43:57.095362+00:00","modified_at":"2020-11-24T14:43:57.095362+00:00","user_count":0},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"}]}}},{"type":"roles","id":"4153333c-2b48-11eb-8472-4f84016f80f7","attributes":{"name":"ruby-List-roles-returns-OK-response-1601469618","created_at":"2020-11-20T15:51:29.853588+00:00","modified_at":"2020-11-20T15:51:29.853588+00:00","user_count":0},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"}]}}}]}'
  recorded_at: Wed, 30 Sep 2020 12:40:18 GMT
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/roles
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"name":"ruby-List_roles_returns_OK_response-1606230446"},"type":"roles"}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/0.1.0 (ruby 2.6.3; os darwin18.7.0; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 24 Nov 2020 15:07:26 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '414'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      Set-Cookie:
      - DD-PSHARD=233; Max-Age=604800; Path=/; expires=Tue, 01-Dec-2020 15:07:26 GMT;
        secure; HttpOnly
      X-Dd-Version:
      - '35.3425088'
      X-Ratelimit-Limit:
      - '500'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '34'
      X-Ratelimit-Remaining:
      - '451'
      X-Dd-Debug:
      - SQ42qDtuEKFP2sgVjIqNlDpiYOKALQoZIabV6hSyHOa0/LSJKKwpuBBfI7vLZopD
      Dd-Pool:
      - dogweb
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"data":{"type":"roles","id":"c36cb034-2e66-11eb-855e-5f482155481f","attributes":{"name":"ruby-List_roles_returns_OK_response-1606230446","created_at":"2020-11-24T15:07:26.514669+00:00","modified_at":"2020-11-24T15:07:26.514669+00:00"},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"}]}}}}'
  recorded_at: Tue, 24 Nov 2020 15:07:26 GMT
- request:
    method: get
    uri: https://api.datadoghq.com/api/v2/roles?filter=ruby-List_roles_returns_OK_response-1606230446
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - datadog-api-client-ruby/0.1.0 (ruby 2.6.3; os darwin18.7.0; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 24 Nov 2020 15:07:26 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '491'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      Set-Cookie:
      - DD-PSHARD=233; Max-Age=604800; Path=/; expires=Tue, 01-Dec-2020 15:07:26 GMT;
        secure; HttpOnly
      X-Dd-Version:
      - '35.3425088'
      X-Ratelimit-Limit:
      - '500'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '34'
      X-Ratelimit-Remaining:
      - '447'
      X-Dd-Debug:
      - 554jtl/SJjxTmK4ElYRM70FG0Y8nm2ZpMLRYU7gYOwQo5oClqUW2XRpaqEBdUJZQ
      Dd-Pool:
      - dogweb
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"meta":{"page":{"total_filtered_count":1,"total_count":67}},"data":[{"type":"roles","id":"c36cb034-2e66-11eb-855e-5f482155481f","attributes":{"name":"ruby-List_roles_returns_OK_response-1606230446","created_at":"2020-11-24T15:07:26.514669+00:00","modified_at":"2020-11-24T15:07:26.514669+00:00","user_count":0},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"}]}}}]}'
  recorded_at: Tue, 24 Nov 2020 15:07:26 GMT
recorded_with: VCR 6.0.0
