---
http_interactions:
- request:
    method: patch
    uri: https://api.datadoghq.com/api/v2/roles/08822b3e-3553-11eb-87b3-afa08ad4760e
    body:
      encoding: UTF-8
      string: '{"data":{"id":"08822b3e-3553-11eb-87b3-afa08ad4760e","type":"roles","attributes":{"name":"ruby-Update_a_role_returns_OK_response-1606991630-updated"}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/0.1.0 (ruby 2.7.1; os darwin19.6.0; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 03 Dec 2020 10:33:50 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '425'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      Set-Cookie:
      - DD-PSHARD=233; Max-Age=604800; Path=/; expires=Thu, 10-Dec-2020 10:33:50 GMT;
        secure; HttpOnly
      X-Dd-Version:
      - '35.3468590'
      X-Ratelimit-Limit:
      - '500'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '10'
      X-Ratelimit-Remaining:
      - '487'
      X-Dd-Debug:
      - D6xOASGs+SeSoSr1onTNqEyFDtjQwnjR937DW7eQT5G8CxiOSfzMZ/Hv6SqRh+8b
      Dd-Pool:
      - dogweb
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"data":{"type":"roles","id":"08822b3e-3553-11eb-87b3-afa08ad4760e","attributes":{"name":"ruby-Update_a_role_returns_OK_response-1606991630-updated","created_at":"2020-12-03T10:33:50.622138+00:00","modified_at":"2020-12-03T10:33:50.850839+00:00"},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"}]}}}}'
  recorded_at: Thu, 03 Dec 2020 10:33:50 GMT
- request:
    method: patch
    uri: https://api.datadoghq.com/api/v2/roles/d02076c2-9909-11eb-9ce8-da7ad0900002
    body:
      encoding: UTF-8
      string: '{"data":{"id":"d02076c2-9909-11eb-9ce8-da7ad0900002","type":"roles","attributes":{"name":"Test-Update_a_role_returns_OK_response-1617955298.945-updated"}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 09 Apr 2021 08:01:42 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '496'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4273965'
      X-Ratelimit-Limit:
      - '500'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '18'
      X-Ratelimit-Remaining:
      - '454'
      X-Dd-Debug:
      - HbtaOKlJ6OCrx9tMXO6ivMTrEM+g0c93HDp08trmOmgdHozC5J+vn10F0H4WPjCU
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"roles","id":"d02076c2-9909-11eb-9ce8-da7ad0900002","attributes":{"name":"Test-Update_a_role_returns_OK_response-1617955298.945-updated","created_at":"2021-04-09T08:01:39.047388+00:00","modified_at":"2021-04-09T08:01:42.800204+00:00"},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"},{"type":"permissions","id":"417ba636-2dce-11eb-84c0-6bce5b0d9de0"}]}}}}'
  recorded_at: Fri, 09 Apr 2021 08:01:38 GMT
- request:
    method: patch
    uri: https://api.datadoghq.com/api/v2/roles/f6472498-990b-11eb-9ce8-da7ad0900002
    body:
      encoding: UTF-8
      string: '{"data":{"id":"f6472498-990b-11eb-9ce8-da7ad0900002","type":"roles","attributes":{"name":"Test-Update_a_role_returns_OK_response-1617956221.96-updated"}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 09 Apr 2021 08:17:02 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '495'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4274158'
      X-Ratelimit-Limit:
      - '500'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '58'
      X-Ratelimit-Remaining:
      - '491'
      X-Dd-Debug:
      - S1wfaMZOKGT/IoMw6fqAwAwGWo2vQ44sjF3YzuETnQfxZO2T5eJbs0aX3UKb9Dwu
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"roles","id":"f6472498-990b-11eb-9ce8-da7ad0900002","attributes":{"name":"Test-Update_a_role_returns_OK_response-1617956221.96-updated","created_at":"2021-04-09T08:17:02.047749+00:00","modified_at":"2021-04-09T08:17:02.210989+00:00"},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"},{"type":"permissions","id":"417ba636-2dce-11eb-84c0-6bce5b0d9de0"}]}}}}'
  recorded_at: Fri, 09 Apr 2021 08:17:01 GMT
- request:
    method: patch
    uri: https://api.datadoghq.com/api/v2/roles/6ac16cce-990d-11eb-9ce8-da7ad0900002
    body:
      encoding: UTF-8
      string: '{"data":{"id":"6ac16cce-990d-11eb-9ce8-da7ad0900002","type":"roles","attributes":{"name":"Test-Update_a_role_returns_OK_response-1617956846-updated"}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 09 Apr 2021 08:27:27 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '492'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4274158'
      X-Ratelimit-Limit:
      - '500'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '33'
      X-Ratelimit-Remaining:
      - '465'
      X-Dd-Debug:
      - HbtaOKlJ6OCrx9tMXO6ivMTrEM+g0c93HDp08trmOmgdHozC5J+vn10F0H4WPjCU
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"roles","id":"6ac16cce-990d-11eb-9ce8-da7ad0900002","attributes":{"name":"Test-Update_a_role_returns_OK_response-1617956846-updated","created_at":"2021-04-09T08:27:26.960453+00:00","modified_at":"2021-04-09T08:27:27.133972+00:00"},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"},{"type":"permissions","id":"417ba636-2dce-11eb-84c0-6bce5b0d9de0"}]}}}}'
  recorded_at: Fri, 09 Apr 2021 08:27:26 GMT
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/roles
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"name":"Test-Update_a_role_returns_OK_response-1617968754"},"type":"roles"}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 09 Apr 2021 11:45:54 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '484'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4275259'
      X-Ratelimit-Limit:
      - '500'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '6'
      X-Ratelimit-Remaining:
      - '414'
      X-Dd-Debug:
      - l8RQo2maZqJf6GFThBbKNE6dvthz6njusVtau3dPXJWL2RLFoN81H+BLPB/1xgs1
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"roles","id":"245cef12-9929-11eb-9ceb-da7ad0900002","attributes":{"name":"Test-Update_a_role_returns_OK_response-1617968754","created_at":"2021-04-09T11:45:54.770775+00:00","modified_at":"2021-04-09T11:45:54.770775+00:00"},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"},{"type":"permissions","id":"417ba636-2dce-11eb-84c0-6bce5b0d9de0"}]}}}}'
  recorded_at: Fri, 09 Apr 2021 11:45:54 GMT
- request:
    method: patch
    uri: https://api.datadoghq.com/api/v2/roles/245cef12-9929-11eb-9ceb-da7ad0900002
    body:
      encoding: UTF-8
      string: '{"data":{"id":"245cef12-9929-11eb-9ceb-da7ad0900002","type":"roles","attributes":{"name":"Test-Update_a_role_returns_OK_response-1617968754-updated"}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 09 Apr 2021 11:45:54 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '492'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4275259'
      X-Ratelimit-Limit:
      - '500'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '6'
      X-Ratelimit-Remaining:
      - '413'
      X-Dd-Debug:
      - dCmL/3rURV6BPeaqeP3Rxigq41m5CAb17XjrRE42uZ01zpr07HVhbL5/3TWMkvgu
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"roles","id":"245cef12-9929-11eb-9ceb-da7ad0900002","attributes":{"name":"Test-Update_a_role_returns_OK_response-1617968754-updated","created_at":"2021-04-09T11:45:54.770775+00:00","modified_at":"2021-04-09T11:45:54.942629+00:00"},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"},{"type":"permissions","id":"417ba636-2dce-11eb-84c0-6bce5b0d9de0"}]}}}}'
  recorded_at: Fri, 09 Apr 2021 11:45:54 GMT
recorded_with: VCR 6.0.0
