---
http_interactions:
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/roles
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"name":"ruby-Update-a-role-returns-OK-response-1601469620"},"type":"roles"}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/0.1.0 (ruby 2.6.3; os darwin18.7.0; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 30 Sep 2020 12:40:20 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '417'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      Set-Cookie:
      - DD-PSHARD=233; Max-Age=604800; Path=/; expires=Wed, 07-Oct-2020 12:40:20 GMT;
        secure; HttpOnly
      X-Dd-Version:
      - '35.3116014'
      X-Ratelimit-Limit:
      - '500'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '40'
      X-Ratelimit-Remaining:
      - '492'
      X-Dd-Debug:
      - cTGY5ulPxaRmdZr4S1APOMLAfMePPA3fkzzqqKyRFf/m5ql3XuUZsd87RDo7B7RR
      Dd-Pool:
      - dogweb
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"data":{"type":"roles","id":"1a37ceda-031a-11eb-b513-8f40f051f61d","attributes":{"name":"ruby-Update-a-role-returns-OK-response-1601469620","created_at":"2020-09-30T12:40:20.882198+00:00","modified_at":"2020-09-30T12:40:20.882198+00:00"},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"}]}}}}'
  recorded_at: Wed, 30 Sep 2020 12:40:20 GMT
- request:
    method: patch
    uri: https://api.datadoghq.com/api/v2/roles/1a37ceda-031a-11eb-b513-8f40f051f61d
    body:
      encoding: UTF-8
      string: '{"data":{"id":"1a37ceda-031a-11eb-b513-8f40f051f61d","type":"roles","attributes":{"name":"ruby-Update-a-role-returns-OK-response-1601469620-updated"}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/0.1.0 (ruby 2.6.3; os darwin18.7.0; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 30 Sep 2020 12:40:21 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '425'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      Set-Cookie:
      - DD-PSHARD=233; Max-Age=604800; Path=/; expires=Wed, 07-Oct-2020 12:40:21 GMT;
        secure; HttpOnly
      X-Dd-Version:
      - '35.3116014'
      X-Ratelimit-Limit:
      - '500'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '39'
      X-Ratelimit-Remaining:
      - '491'
      X-Dd-Debug:
      - kz7POzMRR1DtZrw59X15p2pAWXtFgVtBoSlzXFcGszy5lhwGx7f8GB820VUZODrm
      Dd-Pool:
      - dogweb
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"data":{"type":"roles","id":"1a37ceda-031a-11eb-b513-8f40f051f61d","attributes":{"name":"ruby-Update-a-role-returns-OK-response-1601469620-updated","created_at":"2020-09-30T12:40:20.882198+00:00","modified_at":"2020-09-30T12:40:21.758518+00:00"},"relationships":{"permissions":{"data":[{"type":"permissions","id":"d90f6830-d3d8-11e9-a77a-b3404e5e9ee2"},{"type":"permissions","id":"4441648c-d8b1-11e9-a77a-1b899a04b304"}]}}}}'
  recorded_at: Wed, 30 Sep 2020 12:40:20 GMT
recorded_with: VCR 6.0.0
