http_interactions:
- recorded_at: Tue, 10 Dec 2024 15:40:42 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/rum/applications/abcde-12345
  response:
    body:
      encoding: UTF-8
      string: '{"errors":["Application Not Found not found"]}'
    headers:
      Content-Type:
      - application/json
    status:
      code: 404
      message: Not Found
recorded_with: VCR 6.0.0
