http_interactions:
- recorded_at: Fri, 24 Oct 2025 09:11:32 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/deployment_gates/invalid-gate-id
  response:
    body:
      encoding: UTF-8
      string: '{"errors":[{"status":"400","title":"Bad Request","detail":"attribute
        \"id\" Invalid id"}]}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 400
      message: Bad Request
recorded_with: VCR 6.0.0
