http_interactions:
- recorded_at: Tue, 28 Oct 2025 14:03:30 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/deployment_gates/invalid-gate-id/rules/invalid-rule-id
  response:
    body:
      encoding: UTF-8
      string: '{"errors":[{"status":"400","title":"Bad Request","detail":"attribute
        \"gate_id\" Invalid id"}]}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 400
      message: Bad Request
recorded_with: VCR 6.0.0
