---
http_interactions:
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/TestCreateatagconfigurationreturnsCreatedresponse1618390734/tags
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestCreateatagconfigurationreturnsCreatedresponse1618390734","attributes":{"tags":["app","datacenter"],"metric_type":"distribution"}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Wed, 14 Apr 2021 08:58:54 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '294'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4307086'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '6'
      X-Ratelimit-Remaining:
      - '49'
      X-Dd-Debug:
      - Um4CoU685QqAscnxhS5BD+goWu2yX1Jd4zCfGzSsEvPPIm1qURZaF8dlLl/OEY4I
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestCreateatagconfigurationreturnsCreatedresponse1618390734","attributes":{"tags":["datacenter","app"],"include_percentiles":false,"created_at":"2021-04-14T08:58:54.665032+00:00","updated_at":"2021-04-14T08:58:54.665032+00:00","metric_type":"distribution"}}}'
  recorded_at: Wed, 14 Apr 2021 08:58:54 GMT
recorded_with: VCR 6.0.0
