---
http_interactions:
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/rubyCreateatagconfigurationreturnsCreatedresponse1614797834/tags
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"rubyCreateatagconfigurationreturnsCreatedresponse1614797834","attributes":{"tags":["app","datacenter"],"metric_type":"distribution"}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.7.2; os linux-gnu; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Wed, 03 Mar 2021 18:57:14 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '294'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4022232'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '46'
      X-Ratelimit-Remaining:
      - '49'
      X-Dd-Debug:
      - JpIJLwIH2nFlZOC+u71rq7aAOL43MLZN3MUsL+gpYHdZz5QLUOG8Jysf8kVK6tPU
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"rubyCreateatagconfigurationreturnsCreatedresponse1614797834","attributes":{"tags":["datacenter","app"],"include_percentiles":false,"created_at":"2021-03-03T18:57:14.936299+00:00","updated_at":"2021-03-03T18:57:14.936299+00:00","metric_type":"distribution"}}}'
  recorded_at: Wed, 03 Mar 2021 18:57:14 GMT
recorded_with: VCR 6.0.0
