---
http_interactions:
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/rubyCreateatagconfigurationreturnsCreatedresponse1614797834/tags
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"rubyCreateatagconfigurationreturnsCreatedresponse1614797834","attributes":{"tags":["app","datacenter"],"metric_type":"distribution"}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.7.2; os linux-gnu; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Wed, 03 Mar 2021 18:57:14 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '294'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4022232'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '46'
      X-Ratelimit-Remaining:
      - '49'
      X-Dd-Debug:
      - JpIJLwIH2nFlZOC+u71rq7aAOL43MLZN3MUsL+gpYHdZz5QLUOG8Jysf8kVK6tPU
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"rubyCreateatagconfigurationreturnsCreatedresponse1614797834","attributes":{"tags":["datacenter","app"],"include_percentiles":false,"created_at":"2021-03-03T18:57:14.936299+00:00","updated_at":"2021-03-03T18:57:14.936299+00:00","metric_type":"distribution"}}}'
  recorded_at: Wed, 03 Mar 2021 18:57:14 GMT
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/TestCreateatagconfigurationreturnsCreatedresponse1617955281024/tags
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestCreateatagconfigurationreturnsCreatedresponse1617955281024","attributes":{"tags":["app","datacenter"],"metric_type":"distribution"}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Fri, 09 Apr 2021 08:01:21 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '297'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4273965'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '39'
      X-Ratelimit-Remaining:
      - '49'
      X-Dd-Debug:
      - twvpGlmuom5y6A0pjGtXzTf554cmwJgTcCZ71fK4H/RDi+v5ehBK0zQiRcTJQG5C
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestCreateatagconfigurationreturnsCreatedresponse1617955281024","attributes":{"tags":["datacenter","app"],"include_percentiles":false,"created_at":"2021-04-09T08:01:21.122730+00:00","updated_at":"2021-04-09T08:01:21.122730+00:00","metric_type":"distribution"}}}'
  recorded_at: Fri, 09 Apr 2021 08:01:21 GMT
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/TestCreateatagconfigurationreturnsCreatedresponse1617956198647/tags
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestCreateatagconfigurationreturnsCreatedresponse1617956198647","attributes":{"tags":["app","datacenter"],"metric_type":"distribution"}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Fri, 09 Apr 2021 08:16:38 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '297'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4274158'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '22'
      X-Ratelimit-Remaining:
      - '49'
      X-Dd-Debug:
      - Wjq53IVIwnB4SiR238oOYgHFMq/ZYP0LQ/Dv8C2fFLBwTje/dWJHu6pI6vIOK1zG
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestCreateatagconfigurationreturnsCreatedresponse1617956198647","attributes":{"tags":["datacenter","app"],"include_percentiles":false,"created_at":"2021-04-09T08:16:38.744744+00:00","updated_at":"2021-04-09T08:16:38.744744+00:00","metric_type":"distribution"}}}'
  recorded_at: Fri, 09 Apr 2021 08:16:38 GMT
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/TestCreateatagconfigurationreturnsCreatedresponse1617956828/tags
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestCreateatagconfigurationreturnsCreatedresponse1617956828","attributes":{"tags":["app","datacenter"],"metric_type":"distribution"}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Fri, 09 Apr 2021 08:27:08 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '294'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4274158'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '52'
      X-Ratelimit-Remaining:
      - '49'
      X-Dd-Debug:
      - 2328yjLSqI4XmR1pVqrPRR/SFcQsbafjEpPmZx7/3PfxUK1nJQQsX+wrMelyVyj+
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestCreateatagconfigurationreturnsCreatedresponse1617956828","attributes":{"tags":["datacenter","app"],"include_percentiles":false,"created_at":"2021-04-09T08:27:08.842827+00:00","updated_at":"2021-04-09T08:27:08.842827+00:00","metric_type":"distribution"}}}'
  recorded_at: Fri, 09 Apr 2021 08:27:08 GMT
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/TestCreateatagconfigurationreturnsCreatedresponse1617968737/tags
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestCreateatagconfigurationreturnsCreatedresponse1617968737","attributes":{"tags":["app","datacenter"],"metric_type":"distribution"}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Fri, 09 Apr 2021 11:45:37 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '294'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4275259'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '23'
      X-Ratelimit-Remaining:
      - '49'
      X-Dd-Debug:
      - l4HFlaRP3QwYSqoGKhzbYfv7zgkK63HIRR7YkyVYZspq0lGjjTBwoK8V/alf+XYt
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestCreateatagconfigurationreturnsCreatedresponse1617968737","attributes":{"tags":["datacenter","app"],"include_percentiles":false,"created_at":"2021-04-09T11:45:37.221228+00:00","updated_at":"2021-04-09T11:45:37.221228+00:00","metric_type":"distribution"}}}'
  recorded_at: Fri, 09 Apr 2021 11:45:37 GMT
recorded_with: VCR 6.0.0
