---
http_interactions:
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/rubyDeleteatagconfigurationreturnsNoContentresponse1614797835/tags
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"tags":["app","datacenter","rubyDeleteatagconfigurationreturnsNoContentresponse1614797835"],"metric_type":"distribution"},"type":"manage_tags","id":"rubyDeleteatagconfigurationreturnsNoContentresponse1614797835"}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.7.2; os linux-gnu; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Wed, 03 Mar 2021 18:57:15 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '360'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4022232'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '45'
      X-Ratelimit-Remaining:
      - '47'
      X-Dd-Debug:
      - tpRCH6w417YjBovRJ8VmtuXmNONVYiRp2c8d2AxjPdGBn8PCtgG4vAztrx3qUZAN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"rubyDeleteatagconfigurationreturnsNoContentresponse1614797835","attributes":{"tags":["datacenter","app","rubyDeleteatagconfigurationreturnsNoContentresponse1614797835"],"include_percentiles":false,"created_at":"2021-03-03T18:57:15.108934+00:00","updated_at":"2021-03-03T18:57:15.108934+00:00","metric_type":"distribution"}}}'
  recorded_at: Wed, 03 Mar 2021 18:57:15 GMT
- request:
    method: delete
    uri: https://api.datadoghq.com/api/v2/metrics/rubyDeleteatagconfigurationreturnsNoContentresponse1614797835/tags
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.7.2; os linux-gnu; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 204
      message: No Content
    headers:
      Date:
      - Wed, 03 Mar 2021 18:57:15 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '0'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4022232'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '45'
      X-Ratelimit-Remaining:
      - '46'
      X-Dd-Debug:
      - tpRCH6w417YjBovRJ8VmtuXmNONVYiRp2c8d2AxjPdGBn8PCtgG4vAztrx3qUZAN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: ''
  recorded_at: Wed, 03 Mar 2021 18:57:15 GMT
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/TestDeleteatagconfigurationreturnsNoContentresponse1617955281335/tags
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"tags":["app","datacenter","TestDeleteatagconfigurationreturnsNoContentresponse1617955281335"],"metric_type":"distribution"},"type":"manage_tags","id":"TestDeleteatagconfigurationreturnsNoContentresponse1617955281335"}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Fri, 09 Apr 2021 08:01:21 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '366'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4273965'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '39'
      X-Ratelimit-Remaining:
      - '47'
      X-Dd-Debug:
      - "/L+SFFO+m1pPY+hRCpk5325fvfrNl0KmiquUNJolBN/5hu3HIwflqjZSbJ6NxDFG"
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestDeleteatagconfigurationreturnsNoContentresponse1617955281335","attributes":{"tags":["TestDeleteatagconfigurationreturnsNoContentresponse1617955281335","datacenter","app"],"include_percentiles":false,"created_at":"2021-04-09T08:01:21.433784+00:00","updated_at":"2021-04-09T08:01:21.433784+00:00","metric_type":"distribution"}}}'
  recorded_at: Fri, 09 Apr 2021 08:01:21 GMT
- request:
    method: delete
    uri: https://api.datadoghq.com/api/v2/metrics/TestDeleteatagconfigurationreturnsNoContentresponse1617955281335/tags
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 204
      message: No Content
    headers:
      Date:
      - Fri, 09 Apr 2021 08:01:21 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '0'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4273965'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '39'
      X-Ratelimit-Remaining:
      - '46'
      X-Dd-Debug:
      - SY1h8ScsWq+kYmtbh63ltMLFAZsQjqfrgvdfAoRX+9TzT1sgMBRYaFRwfWWRRe9a
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: ''
  recorded_at: Fri, 09 Apr 2021 08:01:21 GMT
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/TestDeleteatagconfigurationreturnsNoContentresponse161795619901/tags
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"tags":["app","datacenter","TestDeleteatagconfigurationreturnsNoContentresponse161795619901"],"metric_type":"distribution"},"type":"manage_tags","id":"TestDeleteatagconfigurationreturnsNoContentresponse161795619901"}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Fri, 09 Apr 2021 08:16:39 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '364'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4274158'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '21'
      X-Ratelimit-Remaining:
      - '47'
      X-Dd-Debug:
      - vdJ3/nHEY1ioXQ6pQrBVvsQK1s4yyc+wufBMPSoXql71qZVuP/xMdtNo6DafhOAk
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestDeleteatagconfigurationreturnsNoContentresponse161795619901","attributes":{"tags":["datacenter","TestDeleteatagconfigurationreturnsNoContentresponse161795619901","app"],"include_percentiles":false,"created_at":"2021-04-09T08:16:39.112652+00:00","updated_at":"2021-04-09T08:16:39.112652+00:00","metric_type":"distribution"}}}'
  recorded_at: Fri, 09 Apr 2021 08:16:39 GMT
- request:
    method: delete
    uri: https://api.datadoghq.com/api/v2/metrics/TestDeleteatagconfigurationreturnsNoContentresponse161795619901/tags
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 204
      message: No Content
    headers:
      Date:
      - Fri, 09 Apr 2021 08:16:39 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '0'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4274158'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '21'
      X-Ratelimit-Remaining:
      - '46'
      X-Dd-Debug:
      - "/L+SFFO+m1pPY+hRCpk5325fvfrNl0KmiquUNJolBN/5hu3HIwflqjZSbJ6NxDFG"
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: ''
  recorded_at: Fri, 09 Apr 2021 08:16:39 GMT
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/TestDeleteatagconfigurationreturnsNoContentresponse1617956829/tags
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"tags":["app","datacenter","TestDeleteatagconfigurationreturnsNoContentresponse1617956829"],"metric_type":"distribution"},"type":"manage_tags","id":"TestDeleteatagconfigurationreturnsNoContentresponse1617956829"}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Fri, 09 Apr 2021 08:27:09 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '360'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4274158'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '51'
      X-Ratelimit-Remaining:
      - '47'
      X-Dd-Debug:
      - SY1h8ScsWq+kYmtbh63ltMLFAZsQjqfrgvdfAoRX+9TzT1sgMBRYaFRwfWWRRe9a
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestDeleteatagconfigurationreturnsNoContentresponse1617956829","attributes":{"tags":["datacenter","app","TestDeleteatagconfigurationreturnsNoContentresponse1617956829"],"include_percentiles":false,"created_at":"2021-04-09T08:27:09.281567+00:00","updated_at":"2021-04-09T08:27:09.281567+00:00","metric_type":"distribution"}}}'
  recorded_at: Fri, 09 Apr 2021 08:27:09 GMT
- request:
    method: delete
    uri: https://api.datadoghq.com/api/v2/metrics/TestDeleteatagconfigurationreturnsNoContentresponse1617956829/tags
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 204
      message: No Content
    headers:
      Date:
      - Fri, 09 Apr 2021 08:27:09 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '0'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4274158'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '51'
      X-Ratelimit-Remaining:
      - '46'
      X-Dd-Debug:
      - vdJ3/nHEY1ioXQ6pQrBVvsQK1s4yyc+wufBMPSoXql71qZVuP/xMdtNo6DafhOAk
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: ''
  recorded_at: Fri, 09 Apr 2021 08:27:09 GMT
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/TestDeleteatagconfigurationreturnsNoContentresponse1617968737/tags
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"tags":["app","datacenter","TestDeleteatagconfigurationreturnsNoContentresponse1617968737"],"metric_type":"distribution"},"type":"manage_tags","id":"TestDeleteatagconfigurationreturnsNoContentresponse1617968737"}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Fri, 09 Apr 2021 11:45:37 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '360'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4275259'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '23'
      X-Ratelimit-Remaining:
      - '47'
      X-Dd-Debug:
      - S1wfaMZOKGT/IoMw6fqAwAwGWo2vQ44sjF3YzuETnQfxZO2T5eJbs0aX3UKb9Dwu
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestDeleteatagconfigurationreturnsNoContentresponse1617968737","attributes":{"tags":["datacenter","TestDeleteatagconfigurationreturnsNoContentresponse1617968737","app"],"include_percentiles":false,"created_at":"2021-04-09T11:45:37.570995+00:00","updated_at":"2021-04-09T11:45:37.570995+00:00","metric_type":"distribution"}}}'
  recorded_at: Fri, 09 Apr 2021 11:45:37 GMT
- request:
    method: delete
    uri: https://api.datadoghq.com/api/v2/metrics/TestDeleteatagconfigurationreturnsNoContentresponse1617968737/tags
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 204
      message: No Content
    headers:
      Date:
      - Fri, 09 Apr 2021 11:45:37 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '0'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4275259'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '23'
      X-Ratelimit-Remaining:
      - '46'
      X-Dd-Debug:
      - F5gm0Rce1/Abr9/0Fw8HAqWfiz0FdiH8er/AXnN6lOn3L6KyGgbsLCwgPlob1No8
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: ''
  recorded_at: Fri, 09 Apr 2021 11:45:37 GMT
recorded_with: VCR 6.0.0
