---
http_interactions:
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/TestDeleteatagconfigurationreturnsNoContentresponse1618390734/tags
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"tags":["app","datacenter","TestDeleteatagconfigurationreturnsNoContentresponse1618390734"],"metric_type":"distribution"},"type":"manage_tags","id":"TestDeleteatagconfigurationreturnsNoContentresponse1618390734"}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Wed, 14 Apr 2021 08:58:54 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '360'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4307086'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '6'
      X-Ratelimit-Remaining:
      - '47'
      X-Dd-Debug:
      - vdJ3/nHEY1ioXQ6pQrBVvsQK1s4yyc+wufBMPSoXql71qZVuP/xMdtNo6DafhOAk
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestDeleteatagconfigurationreturnsNoContentresponse1618390734","attributes":{"tags":["datacenter","app","TestDeleteatagconfigurationreturnsNoContentresponse1618390734"],"include_percentiles":false,"created_at":"2021-04-14T08:58:54.956893+00:00","updated_at":"2021-04-14T08:58:54.956893+00:00","metric_type":"distribution"}}}'
  recorded_at: Wed, 14 Apr 2021 08:58:54 GMT
- request:
    method: delete
    uri: https://api.datadoghq.com/api/v2/metrics/TestDeleteatagconfigurationreturnsNoContentresponse1618390734/tags
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 204
      message: No Content
    headers:
      Date:
      - Wed, 14 Apr 2021 08:58:55 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '0'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4307086'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '5'
      X-Ratelimit-Remaining:
      - '46'
      X-Dd-Debug:
      - 5gfwVh/5HZ+AnGd/Di93w3NEWC6KMHT9KzmHEiRJmNdOjBtAsbOcgVFyqEChw71h
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: ''
  recorded_at: Wed, 14 Apr 2021 08:58:54 GMT
recorded_with: VCR 6.0.0
