http_interactions:
- recorded_at: Thu, 15 Apr 2021 13:02:11 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"metric_type":"distribution","tags":["app","datacenter","TestDeleteatagconfigurationreturnsNoContentresponse1618491731"]},"id":"TestDeleteatagconfigurationreturnsNoContentresponse1618491731","type":"manage_tags"}}'
    headers:
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Length:
      - '360'
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      Content-Type:
      - application/json
      Date:
      - Thu, 15 Apr 2021 13:02:11 GMT
      Pragma:
      - no-cache
      Strict-Transport-Security:
      - max-age=15724800;
      X-Content-Type-Options:
      - nosniff
      X-Dd-Debug:
      - PhosSd3Ch1B6B0DXI71steKUi7XhPDttnPiIP1NdXTw0VJNWpoUnYyBmODS5ne3q
      X-Dd-Version:
      - '35.4318655'
      X-Frame-Options:
      - SAMEORIGIN
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Remaining:
      - '47'
      X-Ratelimit-Reset:
      - '49'
    method: POST
    uri: https://api.datadoghq.com/api/v2/metrics/TestDeleteatagconfigurationreturnsNoContentresponse1618491731/tags
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestDeleteatagconfigurationreturnsNoContentresponse1618491731","attributes":{"tags":["datacenter","app","TestDeleteatagconfigurationreturnsNoContentresponse1618491731"],"include_percentiles":false,"created_at":"2021-04-15T13:02:11.604097+00:00","updated_at":"2021-04-15T13:02:11.604097+00:00","metric_type":"distribution"}}}'
    status:
      code: 201
      message: Created
- recorded_at: Thu, 15 Apr 2021 13:02:11 GMT
  request:
    body: null
    headers:
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Length:
      - '0'
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      Content-Type:
      - application/json
      Date:
      - Thu, 15 Apr 2021 13:02:13 GMT
      Pragma:
      - no-cache
      Strict-Transport-Security:
      - max-age=15724800;
      X-Content-Type-Options:
      - nosniff
      X-Dd-Debug:
      - fIO2C4qGDheGHy4YbS+r3a3CXbh4cbRo7roILOimQyiHGjQdOat0cIpWCkupM1uX
      X-Dd-Version:
      - '35.4318655'
      X-Frame-Options:
      - SAMEORIGIN
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Remaining:
      - '46'
      X-Ratelimit-Reset:
      - '47'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/metrics/TestDeleteatagconfigurationreturnsNoContentresponse1618491731/tags
  response:
    body:
      encoding: UTF-8
      string: ''
    status:
      code: 204
      message: No Content
- recorded_at: Thu, 15 Apr 2021 13:02:11 GMT
  request:
    body: null
    headers:
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Length:
      - '87'
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      Content-Type:
      - application/json
      Date:
      - Thu, 15 Apr 2021 13:02:13 GMT
      Pragma:
      - no-cache
      Strict-Transport-Security:
      - max-age=15724800;
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Dd-Version:
      - '35.4318655'
      X-Frame-Options:
      - SAMEORIGIN
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Remaining:
      - '45'
      X-Ratelimit-Reset:
      - '47'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/metrics/TestDeleteatagconfigurationreturnsNoContentresponse1618491731/tags
  response:
    body:
      encoding: UTF-8
      string: '{"errors": ["TestDeleteatagconfigurationreturnsNoContentresponse1618491731
        not found"]}'
    status:
      code: 404
      message: Not Found
recorded_with: VCR 6.0.0
