---
http_interactions:
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/TestListtagconfigurationbynamereturnsSuccessresponse1618390735/tags
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"tags":["app","datacenter","TestListtagconfigurationbynamereturnsSuccessresponse1618390735"],"metric_type":"distribution"},"type":"manage_tags","id":"TestListtagconfigurationbynamereturnsSuccessresponse1618390735"}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Wed, 14 Apr 2021 08:58:55 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '362'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4307086'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '5'
      X-Ratelimit-Remaining:
      - '42'
      X-Dd-Debug:
      - vdJ3/nHEY1ioXQ6pQrBVvsQK1s4yyc+wufBMPSoXql71qZVuP/xMdtNo6DafhOAk
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestListtagconfigurationbynamereturnsSuccessresponse1618390735","attributes":{"tags":["TestListtagconfigurationbynamereturnsSuccessresponse1618390735","datacenter","app"],"include_percentiles":false,"created_at":"2021-04-14T08:58:55.976052+00:00","updated_at":"2021-04-14T08:58:55.976052+00:00","metric_type":"distribution"}}}'
  recorded_at: Wed, 14 Apr 2021 08:58:55 GMT
- request:
    method: get
    uri: https://api.datadoghq.com/api/v2/metrics/TestListtagconfigurationbynamereturnsSuccessresponse1618390735/tags
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 14 Apr 2021 08:58:56 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '362'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4307086'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '4'
      X-Ratelimit-Remaining:
      - '41'
      X-Dd-Debug:
      - dCmL/3rURV6BPeaqeP3Rxigq41m5CAb17XjrRE42uZ01zpr07HVhbL5/3TWMkvgu
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestListtagconfigurationbynamereturnsSuccessresponse1618390735","attributes":{"tags":["TestListtagconfigurationbynamereturnsSuccessresponse1618390735","datacenter","app"],"include_percentiles":false,"created_at":"2021-04-14T08:58:55.976052+00:00","updated_at":"2021-04-14T08:58:55.976052+00:00","metric_type":"distribution"}}}'
  recorded_at: Wed, 14 Apr 2021 08:58:55 GMT
recorded_with: VCR 6.0.0
