http_interactions:
- recorded_at: Thu, 15 Apr 2021 13:02:26 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"metric_type":"distribution","tags":["app","datacenter","TestUpdateatagconfigurationreturnsOKresponse1618491746"]},"id":"TestUpdateatagconfigurationreturnsOKresponse1618491746","type":"manage_tags"}}'
    headers:
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Length:
      - '346'
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      Content-Type:
      - application/json
      Date:
      - Thu, 15 Apr 2021 13:02:26 GMT
      Pragma:
      - no-cache
      Strict-Transport-Security:
      - max-age=15724800;
      X-Content-Type-Options:
      - nosniff
      X-Dd-Debug:
      - L3ULR3HwCWYmEqCWGz2Yob3chcH4pjowBacBXkncP7o+/uPqKt9yGEYf/g1AJPzQ
      X-Dd-Version:
      - '35.4318655'
      X-Frame-Options:
      - SAMEORIGIN
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Remaining:
      - '33'
      X-Ratelimit-Reset:
      - '34'
    method: POST
    uri: https://api.datadoghq.com/api/v2/metrics/TestUpdateatagconfigurationreturnsOKresponse1618491746/tags
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestUpdateatagconfigurationreturnsOKresponse1618491746","attributes":{"tags":["datacenter","app","TestUpdateatagconfigurationreturnsOKresponse1618491746"],"include_percentiles":false,"created_at":"2021-04-15T13:02:26.875121+00:00","updated_at":"2021-04-15T13:02:26.875121+00:00","metric_type":"distribution"}}}'
    status:
      code: 201
      message: Created
- recorded_at: Thu, 15 Apr 2021 13:02:26 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"tags":["app"]},"id":"TestUpdateatagconfigurationreturnsOKresponse1618491746","type":"manage_tags"}}'
    headers:
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Length:
      - '276'
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      Content-Type:
      - application/json
      Date:
      - Thu, 15 Apr 2021 13:02:27 GMT
      Pragma:
      - no-cache
      Strict-Transport-Security:
      - max-age=15724800;
      Vary:
      - Accept-Encoding
      X-Content-Type-Options:
      - nosniff
      X-Dd-Debug:
      - B1nwy/pPNqX+q4pQT22cdp1QCexE35IF8qwSHy0Nf7IW0Y881qtn4tXN1lpmzaKc
      X-Dd-Version:
      - '35.4318655'
      X-Frame-Options:
      - SAMEORIGIN
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Remaining:
      - '32'
      X-Ratelimit-Reset:
      - '33'
    method: PATCH
    uri: https://api.datadoghq.com/api/v2/metrics/TestUpdateatagconfigurationreturnsOKresponse1618491746/tags
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestUpdateatagconfigurationreturnsOKresponse1618491746","attributes":{"tags":["app"],"include_percentiles":false,"created_at":"2021-04-15T13:02:26.875121+00:00","updated_at":"2021-04-15T13:02:27.295792+00:00","metric_type":"distribution"}}}'
    status:
      code: 200
      message: OK
- recorded_at: Thu, 15 Apr 2021 13:02:26 GMT
  request:
    body: null
    headers:
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Length:
      - '0'
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      Content-Type:
      - application/json
      Date:
      - Thu, 15 Apr 2021 13:02:27 GMT
      Pragma:
      - no-cache
      Strict-Transport-Security:
      - max-age=15724800;
      X-Content-Type-Options:
      - nosniff
      X-Dd-Debug:
      - bgHykj7A9bfZx0Y5ZO3swhhp5tGUSNJHqFWR868+qg087CYrDOd5hQslC+noiEtH
      X-Dd-Version:
      - '35.4318655'
      X-Frame-Options:
      - SAMEORIGIN
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Remaining:
      - '31'
      X-Ratelimit-Reset:
      - '33'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/metrics/TestUpdateatagconfigurationreturnsOKresponse1618491746/tags
  response:
    body:
      encoding: UTF-8
      string: ''
    status:
      code: 204
      message: No Content
recorded_with: VCR 6.0.0
