---
http_interactions:
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/rubyUpdateatagconfigurationreturnsOKresponse1614797840/tags
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"tags":["app","datacenter","rubyUpdateatagconfigurationreturnsOKresponse1614797840"],"metric_type":"distribution"},"type":"manage_tags","id":"rubyUpdateatagconfigurationreturnsOKresponse1614797840"}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.7.2; os linux-gnu; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Wed, 03 Mar 2021 18:57:20 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '346'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4022232'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '40'
      X-Ratelimit-Remaining:
      - '34'
      X-Dd-Debug:
      - SY1h8ScsWq+kYmtbh63ltMLFAZsQjqfrgvdfAoRX+9TzT1sgMBRYaFRwfWWRRe9a
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"rubyUpdateatagconfigurationreturnsOKresponse1614797840","attributes":{"tags":["datacenter","app","rubyUpdateatagconfigurationreturnsOKresponse1614797840"],"include_percentiles":false,"created_at":"2021-03-03T18:57:20.692813+00:00","updated_at":"2021-03-03T18:57:20.692813+00:00","metric_type":"distribution"}}}'
  recorded_at: Wed, 03 Mar 2021 18:57:20 GMT
- request:
    method: patch
    uri: https://api.datadoghq.com/api/v2/metrics/rubyUpdateatagconfigurationreturnsOKresponse1614797840/tags
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"rubyUpdateatagconfigurationreturnsOKresponse1614797840","attributes":{"tags":["app"]}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.7.2; os linux-gnu; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 03 Mar 2021 18:57:20 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '276'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4022232'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '40'
      X-Ratelimit-Remaining:
      - '33'
      X-Dd-Debug:
      - JpIJLwIH2nFlZOC+u71rq7aAOL43MLZN3MUsL+gpYHdZz5QLUOG8Jysf8kVK6tPU
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"rubyUpdateatagconfigurationreturnsOKresponse1614797840","attributes":{"tags":["app"],"include_percentiles":false,"created_at":"2021-03-03T18:57:20.692813+00:00","updated_at":"2021-03-03T18:57:20.784592+00:00","metric_type":"distribution"}}}'
  recorded_at: Wed, 03 Mar 2021 18:57:20 GMT
recorded_with: VCR 6.0.0
