---
http_interactions:
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/TestUpdateatagconfigurationreturnsOKresponse1617969405/tags
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"tags":["app","datacenter","TestUpdateatagconfigurationreturnsOKresponse1617969405"],"metric_type":"distribution"},"type":"manage_tags","id":"TestUpdateatagconfigurationreturnsOKresponse1617969405"}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Fri, 09 Apr 2021 11:56:45 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '346'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4275259'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '15'
      X-Ratelimit-Remaining:
      - '33'
      X-Dd-Debug:
      - F5gm0Rce1/Abr9/0Fw8HAqWfiz0FdiH8er/AXnN6lOn3L6KyGgbsLCwgPlob1No8
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestUpdateatagconfigurationreturnsOKresponse1617969405","attributes":{"tags":["TestUpdateatagconfigurationreturnsOKresponse1617969405","datacenter","app"],"include_percentiles":false,"created_at":"2021-04-09T11:56:45.636838+00:00","updated_at":"2021-04-09T11:56:45.636838+00:00","metric_type":"distribution"}}}'
  recorded_at: Fri, 09 Apr 2021 11:56:45 GMT
- request:
    method: patch
    uri: https://api.datadoghq.com/api/v2/metrics/TestUpdateatagconfigurationreturnsOKresponse1617969405/tags
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestUpdateatagconfigurationreturnsOKresponse1617969405","attributes":{"tags":["app"]}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 09 Apr 2021 11:56:45 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '276'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4275259'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '15'
      X-Ratelimit-Remaining:
      - '32'
      X-Dd-Debug:
      - fIO2C4qGDheGHy4YbS+r3a3CXbh4cbRo7roILOimQyiHGjQdOat0cIpWCkupM1uX
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestUpdateatagconfigurationreturnsOKresponse1617969405","attributes":{"tags":["app"],"include_percentiles":false,"created_at":"2021-04-09T11:56:45.636838+00:00","updated_at":"2021-04-09T11:56:45.863994+00:00","metric_type":"distribution"}}}'
  recorded_at: Fri, 09 Apr 2021 11:56:45 GMT
- request:
    method: post
    uri: https://api.datadoghq.com/api/v2/metrics/TestUpdateatagconfigurationreturnsOKresponse1617971029/tags
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"tags":["app","datacenter","TestUpdateatagconfigurationreturnsOKresponse1617971029"],"metric_type":"distribution"},"type":"manage_tags","id":"TestUpdateatagconfigurationreturnsOKresponse1617971029"}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Fri, 09 Apr 2021 12:23:49 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '346'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4275715'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '11'
      X-Ratelimit-Remaining:
      - '33'
      X-Dd-Debug:
      - nLnnBNvlCFDECRnZvzDb0z4sAO35G+IMidcAs8vrCKyjvsKWE8Yd9S3n6OjZ1qRN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestUpdateatagconfigurationreturnsOKresponse1617971029","attributes":{"tags":["datacenter","app","TestUpdateatagconfigurationreturnsOKresponse1617971029"],"include_percentiles":false,"created_at":"2021-04-09T12:23:49.415862+00:00","updated_at":"2021-04-09T12:23:49.415862+00:00","metric_type":"distribution"}}}'
  recorded_at: Fri, 09 Apr 2021 12:23:49 GMT
- request:
    method: patch
    uri: https://api.datadoghq.com/api/v2/metrics/TestUpdateatagconfigurationreturnsOKresponse1617971029/tags
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestUpdateatagconfigurationreturnsOKresponse1617971029","attributes":{"tags":["app"]}}}'
    headers:
      User-Agent:
      - datadog-api-client-ruby/1.0.0.beta.3.dev (ruby 2.6.3; os darwin19; arch x86_64)
      Content-Type:
      - application/json
      Accept:
      - application/json
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 09 Apr 2021 12:23:49 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '276'
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Version:
      - '35.4275715'
      X-Ratelimit-Limit:
      - '50'
      X-Ratelimit-Period:
      - '60'
      X-Ratelimit-Reset:
      - '11'
      X-Ratelimit-Remaining:
      - '32'
      X-Dd-Debug:
      - gYZcaADwbKcv7Hm19HJx6WsLoKuOijDWAt2viPeCfWqUgyKY+9e1xZdmMJeXV3YV
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"data":{"type":"manage_tags","id":"TestUpdateatagconfigurationreturnsOKresponse1617971029","attributes":{"tags":["app"],"include_percentiles":false,"created_at":"2021-04-09T12:23:49.415862+00:00","updated_at":"2021-04-09T12:23:49.579470+00:00","metric_type":"distribution"}}}'
  recorded_at: Fri, 09 Apr 2021 12:23:49 GMT
recorded_with: VCR 6.0.0
