name: IntegrationTests
trigger:
  batch: false
  branches:
    include:
    - master
pr:
  branches:
    include:
    - master
  drafts: false
schedules:
  - cron: "45 1-23/3 * * *"
    displayName: Scheduled CI run every 3 hours
    always: true
    branches:
      include:
        - master

resources:
  containers:
  - container: datadog-agent
    image: datadog/agent:latest
    ports:
    - 8126:8126
    env:
      DD_API_KEY: $(ddAPIKey)
      DD_HOSTNAME: "none"
      DD_INSIDE_CI: "true"
jobs:
- job: IntegrationTests
  pool:
    vmImage: "Ubuntu-16.04"
  container:
    image: ruby:2.7
  services:
    datadog-agent: datadog-agent
  steps:
    - script: bundle install
    - script: ./run-tests.sh
      displayName: Run integration tests
      env:
        CI: "true"
        DD_AGENT_HOST: datadog-agent
        DD_ENV: prod
        DD_SERVICE: datadog-api-client-ruby
        DD_TAGS: "team:integration-tools-and-libraries"
        DD_TEST_CLIENT_API_KEY: $(datadogAPIKey)
        DD_TEST_CLIENT_APP_KEY: $(datadogAPPKey)
        DD_TRACE_ANALYTICS_ENABLED: "true"
        RECORD: "none"
