name: Reusable Examples Workflow

on:
  workflow_call:
    inputs:
      target-branch:
        description: 'Branch to checkout and test (defaults to the calling branch)'
        required: false
        type: string
        default: ''
      examples-script:
        description: 'Examples script to execute'
        required: false
        type: string
        default: './check-examples.sh'
      cache-version:
        description: 'Cache version for gem dependencies'
        required: false
        type: string
        default: ''

jobs:
  examples:
    runs-on: ubuntu-latest
    env:
      DD_PROFILING_NO_EXTENSION: true
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          repository: DataDog/datadog-api-client-ruby
          ref: ${{ inputs.target-branch || github.ref }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@dffb23f65a78bba8db45d387d5ea1bbd6be3ef18 # v1.293.0
        with:
          ruby-version: "2.7"
          bundler-cache: true
          cache-version: ${{ inputs.cache-version }}
      - name: Check examples
        run: ${{ inputs.examples-script }}
        shell: bash