name: Reusable Examples Workflow

on:
  workflow_call:
    inputs:
      target-branch:
        description: 'Branch to checkout and test (defaults to the calling branch)'
        required: false
        type: string
        default: ''
      examples-script:
        description: 'Examples script to execute'
        required: false
        type: string
        default: './check-examples.sh'
      cache-version:
        description: 'Cache version for gem dependencies'
        required: false
        type: string
        default: ''

jobs:
  examples:
    runs-on: ubuntu-latest
    env:
      DD_PROFILING_NO_EXTENSION: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: DataDog/datadog-api-client-ruby
          ref: ${{ inputs.target-branch || github.ref }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: "2.7"
          bundler-cache: true
          cache-version: ${{ inputs.cache-version }}
      - name: Check examples
        run: ${{ inputs.examples-script }}
        shell: bash